DRAFT-WIP: Harvester #2096 Local Test Rancher Infrastructure Enhancement (air-gapped)
harvester/ipxe-examples pull request #45
Opened 2022-04-19 02:47 UTC by irishgordo

## What this PR Is Trying To Accomplish:
- lay a foundation on which we can leverage the pre-existing vagrant, libvirt/vagrant-libvirt, ansible, and ipxe harvester cluster creation for testing but introducing the ability to spin up a single node air-gapped rancher instance/vm that has a private registry, loads in content, then cuts a 'public' network to shift over to only using the existing 'harvester network' that's private.  Once this is more stable and with additional edits we would hopefully be able to run both Rancher and Harvester automated smoke tests or e2e's against the local Vagrant-Ansible-Libvirt/Vagrant-Libvirt local test VM setup.

## TODOS:
- squash commits after stability has been achieved and PR is ready
- switch all shell commands over to the appropriate ansible module, was currently having trouble getting the modules to work as expected
- automate the remaining harvester steps from [#1808 - that have been documented](https://github.com/harvester/harvester/issues/1808)
- fix routing issue, currently the workaround is to do something like this:
  - on harvester node:
      - ssh in as rancher@harvester_ip, `sudo cat /etc/rancher/rke2/rke2.yaml ` copy that over to a kubeconfig you have locally, ~/.kube/harvester_node.yaml, modify the 127.0.0.1 IP to that of the harvester_node_ip
       - perform a port forward, so locally you can view the harvester-rancher-ui, something like: `kubectl --kubeconfig ~/.kube/harvester_node.yaml port-forward -n cattle-system service/rancher 7443:443 `
   - on rancher node:
      - ssh in as vagrant@rancher_node_ip, grab the `cat ~/.kube/config/k3s.yaml`, modify the 127.0.0.1 IP to that of the rancher_node_ip saving it as another kubeconfig
      - perform a port forward to rancher's rancher-ui , `kubectl --kubeconfig ~/.kube/local-rancher-vm.yaml port-forward -n cattle-system service/rancher 8443:443`  
- modify the tasks for the rancher-vm, ansible playbook to remove the 'ignore' failures boolean flag, once it's more 'stable'
      
## Additional Enhancements:
- it's very slow, destroying it with a `vagrant destroy` and rebuilding takes time, since both the Docker image registry and the Rancher instance are on the same VM... we may want to separate them out, find more persistent storage for how the Docker registry exists, that way not every time will we have to download all rancher images for a given version over the internet, but rather they may already exist in the registry and the registry might be taking advantage of some kind of other data-store like an NFS VM or something
- it struggles with being consistently successful upon ./setup_harvester command
- adjust CPU/Memory/Disk based around what we think is needed - at times, the disk will consume as much as 166GiB due to the tar-ing/gunzipping of some of the files before they're loaded

## To Run:
- All setting edits get made in the settings.yaml, you can adjust different versions of content there, spinning up the cluster is the same with the `./setup_harvester.sh` command to kick everything off - **warning: this does take up to 2.5 hours to provision everything - and is dependent on internet speed**

![Screenshot from 2022-04-18 18-53-01](https://user-images.githubusercontent.com/5370752/163910034-bdff9b76-b571-4656-9d2b-3069db2a1137.png)

![Screenshot from 2022-04-18 18-49-37](https://user-images.githubusercontent.com/5370752/163910070-2a1a8314-0812-43ca-937f-ff30366de081.png)

2022-04-22 03:37 UTC, irishgordo commented
@noahgildersleeve @TachunLin  - this should mostly be ready to go to test out and run.
Keeping the settings how they are currently in the settings.yaml could work (might want to adjust cpu/mem) but then just running with: `./setup_harvester.sh` it'll take a while and is dependent on internet speed.
The last run I had started at **16:41** and finished at **18:39** (roughly) with symmetrical 1 GiB Up/Down.
Once it's finished, you just navigate to whatever you named your Rancher url-instance like: "https://helm-install.test
And also navigate to the single node harvester instance ex: https://192.168.0.30 
And just in Rancher import existing Harvester - then add that cluster registration url to the single Harvester node and it will work.

What isn't set up, is 'testing' VM creation in Harvester... that will take some more fancy SLES OpenStack management and other things, which I'd love to pair on with either one of you or others to try to figure out... since right now, the only thing immediately available to test is just 'does air-gapped rancher' import an offline/air-gapped 'harvester' instance.

This automation is 'extremely' slow... I think we can definitely iterate and find a better solution moving forward :sweat_smile: - but for now it 'mostly' works :smile: 

Super willing to make changes, iterate, pair, etc. on this :smile:

2022-04-25 21:26 UTC, irishgordo commented
Note:
- harvester/tests - the test_rancher_integration.py fails with airgapped rancher/harvester combination:
    - test_create_rke2_cluster fails (also couldn't clean up cloud credential)
    - test_create_rke1_cluster fails as well
    
Attaching a test log.
Both are timeouts mainly.
The cloud credential cleanup on delete tossed back a 422.

[rancher_integration_tests_failures_with_airgapped_rancher_and_harvester.log](https://github.com/harvester/ipxe-examples/files/8558093/rancher_integration_tests_failures_with_airgapped_rancher_and_harvester.log)

X-Ref: https://github.com/harvester/tests

2022-05-03 20:12 UTC, noahgildersleeve submitted a review, later dismissed
It mostly looks good although I'll take another look at the airgapped section later. We need to change a couple of settings and update the readme a little.

2022-05-03 20:12 UTC, noahgildersleeve commented on vagrant-pxe-harvester/README.md
> +    needs. The options are self-documented.
We should add in the settings for rancher airgapped to work as a sub-bullet in the README.md. There's three of them or so and they should be documented.

2022-05-20 00:11 UTC, irishgordo commented
did a few edits, still testing it, then I'll add the additional edits to this - wanna ensure that it's not breaking:
https://github.com/irishgordo/ipxe-examples/tree/feat/2096-iteration-extra-explore-branch/vagrant-pxe-harvester

2022-05-23 02:56 UTC, irishgordo commented
I built a temporary Jenkins pipelineJob, that demonstrates a PoC of build parameters dictating what ecosystem of Harvester to spin up here:
https://gist.github.com/irishgordo/c05dffaac0c4d0d036ac5cd7cea9d321

2022-05-25 14:56 UTC, TachunLin requested changes
Hi @irishgordo, that's really an important enhancement for the air gapped feature testing, thanks for the great effort. 
I tried to clone it, modified the offline feature in settings.yml and run the ./setup_harvester.sh to start the air gapped environment. 

It can't finish the provisioning of the `rancher_box` machine.  
I encounter failure in the following tasks:

* **TASK** `[download k3s]`
  ```
  msg: 'Request failed: <urlopen error timed out>'
        url: https://github.com/k3s-io/k3s/releases/download/v1.23.4%2Bk3s1/k3s
  ```
  ![image](https://user-images.githubusercontent.com/29251855/170283301-ad94ba6c-ab4a-43b1-a9b4-59ee5c5f98e5.png)
 
 * **TASK** `[install k8s ansible controlling modules from ansible galaxy] `
    ```
    `ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/v2/collections/kubernetes/core/': <urlopen error [Errno 101] Network is unreachable>`
    ```
    ![image](https://user-images.githubusercontent.com/29251855/170292503-23553264-010d-49ff-a177-b8e557e174bd.png)

* Sometimes it can proceed then failed at the **TASK** `[get helm key] `
  `Failed to connect to baltocdn.com port 443: Connection refused`
  ![image](https://user-images.githubusercontent.com/29251855/170199290-6b728cce-c9bf-4762-8346-146fbcca44f2.png)
  ```
  - name: get helm key
  shell: |
  curl https://baltocdn.com/helm/signing.asc | apt-key add -
  register: helm_key_result
  ```

Not sure whether it's related to the network stability through the pxe_server http proxy.

2022-05-26 03:43 UTC, irishgordo commented
I've also added some additional debugging on the Vagrant and Ansible level with a recent push that injects additional env variables in the same CLI:
```
VAGRANT_LOG=info ANSIBLE_DEBUG=true ANSIBLE_VERBOSITY=3 
```
in ./setup_harvester.sh - so that may help also provide a bit more insight hopefully, I'm spinning one up now on my local instance of Jenkins - though the local instance pipelines I've been still working through a bit:
http://72.193.164.47:8080/job/harvester-vagrant-install-testing-pipeline-job/74/console

2022-05-26 13:44 UTC, TachunLin commented
@irishgordo , I tested the latest commit changes in [93efee1](https://github.com/harvester/ipxe-examples/commit/93efee1ad7bef69fc8e65fdf93dcb1c23a37f59b)
1. Add `VAGRANT_LOG=info` 
2. `ANSIBLE_DEBUG=true ANSIBLE_VERBOSITY=3` 

 with the following config in settings.yml
  ```
  harvester_cluster_nodes: 1
  
  harvester_network_config:
    offline: true
  
  rancher_config:
    run_single_node_air_gapped_rancher: true
  ```

The provisioning of rancher_box failed twice on the `TASK [grab ansible and galaxy]`
The error sterr is: 
```
msg: non-zero return code
      rc: 1
      start: '2022-05-26 11:05:21.626273'
      stderr: |-
        [WARNING]: Skipping Galaxy server https://galaxy.ansible.com. Got an unexpected
        error when getting available versions of collection kubernetes.core: Unknown
        error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/':
        <urlopen error [Errno -3] Temporary failure in name resolution>
        ERROR! Unknown error when attempting to call Galaxy at 'https://galaxy.ansible.com/api/': <urlopen error [Errno -3] Temporary failure in name resolution>
      stderr_lines: <omitted>
``` 

  ![image](https://user-images.githubusercontent.com/29251855/170499727-d83f5f7d-9e3b-4960-b942-b349bc1a29c7.png)
  ![image](https://user-images.githubusercontent.com/29251855/170499797-2a281a94-1728-41c9-8459-3664cfcfdfe5.png)


For more detailed log can refer to the attachment:
[pr45_2.log](https://github.com/harvester/ipxe-examples/files/8779281/pr45_2.log)

And since by adding the debugging on Vagrant and Ansible level, the console log would become pretty large. 
Maybe we  can remove this config after we settle down everything

2022-05-26 14:34 UTC, TachunLin commented
Besides I also tested the configuration matrix of `offline` and `run_single_node_air_gapped_rancher`
Try to figure out whether we can achieve the on/off switch feature between air-gapped and internet environment. 

|                      | offline=true | offline=false |
|----------------------|--------------|---------------|
| airgap rancher=true  |   Air gap    |    Internet   |
| airgap rancher=false |   Skipped    |    Skipped    |

1. Once we set `airgap rancher=false = false`, none of the rancher_boxed will be deployed, they will be skipped
2. Set `offline=true` and `airgap rancher=true` is the default design for both air gapped harvester and rancher
3. Set `offline=false` and `airgap rancher=true`, we can have the internet harvester and rancher 

Another thing that worth take a look is once we set the harvester `node: 1`
(In this case, I marked most of the tasks in set_rancher_node.yml to speed up the process)

The TASK `[making adjustments]` would failed. 
```
fatal: [192.168.0.32]: UNREACHABLE! => changed=false 
  msg: 'Failed to connect to the host via ssh: ssh: connect to host 192.168.0.32 port 22: No route to host'
  unreachable: true
fatal: [192.168.0.31]: UNREACHABLE! => changed=false 
  msg: 'Failed to connect to the host via ssh: ssh: connect to host 192.168.0.31 port 22: No route to host'
  unreachable: true
fatal: [192.168.0.33]: UNREACHABLE! => changed=false 
  msg: 'Failed to connect to the host via ssh: ssh: connect to host 192.168.0.33 port 22: No route to host'
```

![image](https://user-images.githubusercontent.com/29251855/170475095-155f4c3c-a823-4f6d-94dd-05ca7a390b9a.png)
![image](https://user-images.githubusercontent.com/29251855/170475146-05a910e4-157c-4498-a139-f211fc17815e.png)

Not sure whether we can avoid this by setting the appropriate IP address in the settings.yml file.

2022-05-27 00:43 UTC, irishgordo commented
starting to notice that almost any task that requires us to fetch something, probably should be wrapped in some retries.
I've now just recently also seen the task for downloading cert manager credentials fail, I'll be refactoring this so that all tasks that need to download something, get wrapped with some retries.  I think it's just network in-consistencies that tends to be causing these issues.

2022-05-28 12:34 UTC, TachunLin commented
Tested the commit [d19cbd0](https://github.com/harvester/ipxe-examples/commit/d19cbd0e23d036ed1a8fd18a30945b121ac4a005) with some retries and delays

This time the rancher_box provisioning would failed with the following error message

```
 ERROR! couldn't resolve module/action 'community.general.parted'. This often indicates a misspelling, missing collection, or incorrect module path.

    The error appears to be in '/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45-2/ipxe-examples/vagrant-pxe-harvester/ansible/setup_rancher_node.yml': line 15, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.

    The offending line appears to be:


        - name: Create a new ext4 primary partition
          ^ here

```
![image](https://user-images.githubusercontent.com/29251855/170825698-78c4f761-44f8-4e60-bd5e-937916ddb3a2.png)

2022-05-30 19:18 UTC, irishgordo commented
@TachunLin oh!
I forgot to update the readme to disclose that `ansible-galaxy collection install community.general` is a dependency, anytime the rancher_box provisioning runs.
Thank you for catching that!
I've pushed up an update that does update the README with that information.  
I also for some reason have been running into this error:
```
  stderr: |-
    Error: chart requires kubeVersion: < 1.24.0-0 which is incompatible with Kubernetes v1.24.0
 ```
 on the:
  ```
    cmd:
  - helm
  - template
  - rancher
  - /home/vagrant/rancher-2.6.5.tgz
  - --output-dir
  - /home/vagrant
  - --no-hooks
  - --namespace
  - cattle-system
  - --set
  - hostname=helm-install.test
  - --set
  - rancherImageTag=v2.6.5
  - --set
  - rancherImage=myregistry.local:5000/rancher/rancher
  - --set
  - systemDefaultRegistry=myregistry.local:5000
  - --set
  - useBundledSystemChart=true
  - --set
  - ingress.tls.source=secret
  - --set
  - privateCA=true
  ```
 Provisioning step.  I'm thinking it may be a conflict within K3s.  I'm testing it now, but in the push, I also have decreased K3s to a prior version by default.

2022-05-30 23:14 UTC, irishgordo commented
@TachunLin 
Just pushed up some changes, that should fix the additional error I was seeing with `kubeVersion`.
Passing the `--validate` flag into the `helm template` command seems to have remedied the situation.
Not entirely sure why that error got generated now, when I previously wasn't seeing it running the provisioning - but it should be fixed now :smile:

2022-05-31 09:24 UTC, TachunLin commented
Tested the update commit [fe3b8cb](https://github.com/harvester/ipxe-examples/commit/fe3b8cbf03f3b6c64e576bc6c7fae35aa5ce465c) twice. 
It will stop at the task: `name: Create a new ext4 primary partition` 

Suppose it may be related to the ansible/setup_pxe_server.yml

```
 ERROR! couldn't resolve module/action 'community.general.parted'. This often indicates a misspelling, missing collection, or incorrect module path.
  
    The error appears to be in '/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0531/ipxe-examples/vagrant-pxe-harvester/ansible/setup_rancher_node.yml': line 15, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
        - name: Create a new ext4 primary partition
          ^ here
  stdout_lines: <omitted>

```

![image](https://user-images.githubusercontent.com/29251855/171138349-89775f1f-a02b-41ed-aa85-e08a8a2d17eb.png)

* Complete log file for reference:
[review_failure.log](https://github.com/harvester/ipxe-examples/files/8803828/review_failure.log)

2022-06-01 11:52 UTC, TachunLin commented
Tested three times by running the `ansible-galaxy collection install community.general` before executing the `setup_harvester.sh`

```
davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0601/ipxe-examples/vagrant-pxe-harvester> ansible-galaxy collection install community.general
Process install dependency map
Starting collection install process
Skipping 'community.general' as it is already installed
```

But still get the same error as it was in the previous trials.
```
ERROR! couldn't resolve module/action 'community.general.parted'. This often indicates a misspelling, missing collection, or incorrect module path.
 The error appears to be in '/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0601/ipxe-examples/vagrant-pxe-harvester/ansible/setup_rancher_node.yml': line 15, column 7, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
  
        - name: Create a new ext4 primary partition
          ^ here
  stdout_lines: <omitted>
```
https://github.com/harvester/ipxe-examples/pull/45#issuecomment-1141891264

2022-06-02 23:56 UTC, irishgordo commented
@TachunLin  after a bit of digging I believe the issue you're seeing is related to your Python & PIP environment.

When you installed Ansible did you install it via pip?

### Initial Analysis 
Re-reading through my history file in setting up my environment, I believe I may have taken a hybrid approach, to install with the package manager but then ultimately override the install with pip, but it may have allowed for necessary packages to get created.

Originally I see:
```
  133  3/28/2022 18:13  apt search ansible
  134  3/28/2022 18:13  sudo apt install ansible
  135  3/28/2022 18:13  apt search vagrant-libvirt
  136  3/28/2022 18:14  sudo apt install vagrant-libvirt
```
in my history.

It does look like I ultimately overwrote the default installed Ansible with a `pyenv` based one:
```
suse-workstation-team-harvester➜  vagrant-pxe-harvester : feat/2096-air-gapped-rancher-single-node-proof-of-concept ✘ :✭ ᐅ  pyenv which ansible
/home/mike/.pyenv/versions/3.8.13/bin/ansible
```
&
```
suse-workstation-team-harvester➜  vagrant-pxe-harvester : feat/2096-air-gapped-rancher-single-node-proof-of-concept ✘ :✭ ᐅ  whereis ansible
ansible: /usr/bin/ansible /home/mike/.pyenv/shims/ansible /usr/share/man/man1/ansible.1.gz

```

I never removed the `ansible` tied to my apt:
```
suse-workstation-team-harvester➜  vagrant-pxe-harvester : feat/2096-air-gapped-rancher-single-node-proof-of-concept ✘ :✭ ᐅ  apt search ansible
Sorting... Done
Full Text Search... Done
ansible/jammy,jammy,now 2.10.7+merged+base+2.10.8+dfsg-1 all [installed]
  Configuration management, deployment, and task execution system
```
- since the .pyenv/shim based ansible, that version is core 2.13.0 and the one from `apt` that version is via an `apt info ansible` 2.10.7...

### Possible Fixes:
- You might try trying to update your version of Ansible, then re-install the `community.general` ansible galaxy collection passing a `--force` at the end after the ansible upgrade I noticed currently you're running:
```
    ansible-playbook 2.9.21
      config file = /home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0531/ipxe-examples/vagrant-pxe-harvester/ansible.cfg
      configured module search path = ['/home/davidtclin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
      ansible python module location = /usr/lib/python3.6/site-packages/ansible
      executable location = /usr/bin/ansible-playbook
      python version = 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
```
I'm running 2.13.0 on python 3.8.13:
```
suse-workstation-team-harvester➜  ~  ᐅ  ansible-playbook --version
/home/mike/.pyenv/versions/3.8.13/lib/python3.8/site-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,
ansible-playbook [core 2.13.0]
  config file = None
  configured module search path = ['/home/mike/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/mike/.pyenv/versions/3.8.13/lib/python3.8/site-packages/ansible
  ansible collection location = /home/mike/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/mike/.pyenv/versions/3.8.13/bin/ansible-playbook
  python version = 3.8.13 (default, Mar 28 2022, 17:40:36) [GCC 11.2.0]
  jinja version = 3.1.2
  libyaml = True
```

### Replicating Your Issue:
- I was able to replicate your issue around the error of seeing "name: "... with the reference to "parted" that comes from the community.general ansible-galaxy collection.  When I was on my test Jenkins instance, I found that was the case when I had installed Ansible via "pip" perhaps an incorrect way:
```
jenkins@jenkins:~$ history | grep -C 4 -ie "ansible" | grep -ie "pip"
  313  python3 -m pip install --user ansible
  314  python3 -m pip3 install --user ansible
  315  curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  324  python3 -m pip install --user ansible
  340  python3 -m pip install --user ansible
  341  python3 -m pip install --user ansible-playbook
  358  python3 -m pip install --user ansible-playbook
  359  python3 -m pip uninstall ansible
  374  python3 -m pip uninstall ansible
  375  pip uninstall ansible --use
  376  python3 -m pip uninstall ansible --user
  378  pip freeze
  379  pip uninstall ansible --force
  380  pip uninstall
  381  pip uninstall ansible
  382  pip uninstall ansible-core
  427  history | grep -C 4 -ie "ansible" | grep -ie "pip"
```
I ultimately uninstalled it via pip and installed it via `apt` on the server, and the ansible version I'm now then running their is:
```
jenkins@jenkins:~$ ansible --version
ansible 2.10.8
  config file = None
  configured module search path = ['/home/jenkins/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.10.4 (main, Apr  2 2022, 09:04:19) [GCC 11.2.0]
```

My guess is that the error may be related to the version of Ansible that you have, but I'm still not 100% sure.

2022-06-03 15:38 UTC, irishgordo commented
Note, v2.6.5, with the way we create a template from that tarballed air-gapped rancher package, may not currently work, I'll be dropping the version to the latest `rc` from 2.6.4-* and try today.  X-Ref: https://github.com/rancher/rancher/issues/37779

2022-06-08 02:12 UTC, TachunLin commented
@irishgordo. I tested twice on the latest commit [0dd1cce](https://github.com/harvester/ipxe-examples/commit/0dd1cce6641525fbe11c59a533c732cfabf2c65b). 

After upgrading Ansible to 2.10.17 and 4.2.0, we can proceed the previous failure task
`name: Create a new ext4 primary partition`

The follow up process **failed** at the 
` TASK [grab base packages for vagrant rancher single node]`
With the error message
```
<192.168.0.34> Failed to connect to the host via ssh: Shared connection to 192.168.0.34 closed.
    <192.168.0.34> ESTABLISH SSH CONNECTION FOR USER: vagrant
    <192.168.0.34> SSH: EXEC ssh -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o IdentityFile=/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0607/ipxe-examples/vagrant-pxe-harvester/.vagrant/machines/rancher_box/libvirt/private_key -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="vagrant"' -o ConnectTimeout=30 -o ControlPath=/home/davidtclin/.ansible/cp/e43e363605 192.168.0.34 '/bin/sh -c '"'"'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1654617270.988283-30209-62278863384720/ > /dev/null 2>&1 && sleep 0'"'"''
```

* Log file
[failure_log01.txt](https://github.com/harvester/ipxe-examples/files/8857728/failure_log01.txt)
[failure_log02.txt](https://github.com/harvester/ipxe-examples/files/8857729/failure_log02.txt)

2022-06-08 21:10 UTC, irishgordo commented
@TachunLin thanks for re-running the build!
I'm digging in to what can be done with that :smile: - thinking it may have something to do with the way the ssh is set up for the rancher vm.

2022-06-10 22:08 UTC, irishgordo commented
Updated the README to also include that the program `sshpass` is a dependency now locally.

2022-06-14 11:19 UTC, TachunLin commented
@irishgordo, thanks for the check and the effort to updating new commits. 
I tests the commit [addfa0b](https://github.com/harvester/ipxe-examples/commit/addfa0b8b28f3dbc54865433133639cb788aeb0d), this time the provisioning last more than **3.5 hours** until it stops at the following stage with error
  ```
  INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x00007fceecbc5800>
      /home/davidtclin/.vagrant.d/gems/2.7.4/gems/vagrant-libvirt-0.9.0/lib/vagrant-libvirt/action/resolve_disk_settings.rb:101:in `lookup_domain_by_uuid': no implicit conversion of nil into String (TypeError)
  ```

![image](https://user-images.githubusercontent.com/29251855/173564942-d1948f5d-a885-4b7c-afdf-822f647d3257.png)

I am thinking whether this error comes from the ruby version and not sure whether we have already finished the rancher_box provisioning. 
Perhaps the console log output contain more details for your reference.
[failure_log.txt](https://github.com/harvester/ipxe-examples/files/8899227/failure_log.txt)

2022-06-15 22:46 UTC, irishgordo commented
@TachunLin as far as I can tell that seems to be because of Vagrantfile isn't yet compatible with `vagrant-libvirt-0.9.0` - I had some success uninstalling `vagrant-libvirt` then installing it:
```
vagrant plugin install vagrant-libvirt --plugin-version=0.8.2
```
0.9.0 came out about a week ago and seems to be causing problems.

2022-06-17 08:29 UTC, TachunLin commented
Hi @irishgordo, you are right it works after updating the vagrant-libvirt from 0.7.0 to 0.8.2 
I tried twice yesterday, the first trial get ssh connect error. 
The second trial got a good result. :+1: 
* While the second trial I first time complete the pxe_server, rancher_box and harvester-node1 provisioning process. 
  ![image](https://user-images.githubusercontent.com/29251855/174258391-9cbab023-3862-42ad-b9ac-b813863ec6ba.png)

* I found another issue is the harvester-node seems not able to be detected in the Task [making adjustments]
  But the harvester node vm is running and reachable.
![image](https://user-images.githubusercontent.com/29251855/174258331-31af4c6e-b5a9-45ba-af1c-139fcc8694f3.png)

```
TASK [making adjustments] ********************************************************************************************************************************************************************
fatal: [192.168.0.30]: UNREACHABLE! => changed=false 
  msg: |-
    Failed to connect to the host via ssh: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    @    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
    @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
    IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
    Someone could be eavesdropping on you right now (man-in-the-middle attack)!
    It is also possible that a host key has just been changed.
    The fingerprint for the ECDSA key sent by the remote host is
    SHA256:whfU81YmnSOiPHT4ykiXB1s4fjiPA0PodWRq70w8sQ0.
    Please contact your system administrator.
    Add correct host key in /home/davidtclin/.ssh/known_hosts to get rid of this message.
    Offending ECDSA key in /home/davidtclin/.ssh/known_hosts:80
    You can use following command to remove the offending key:
    ssh-keygen -R 192.168.0.30 -f /home/davidtclin/.ssh/known_hosts
    Password authentication is disabled to avoid man-in-the-middle attacks.
    Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
    rancher@192.168.0.30: Permission denied (publickey,password,keyboard-interactive).
  unreachable: true
fatal: [192.168.0.32]: UNREACHABLE! => changed=false 
  msg: 'Failed to connect to the host via ssh: ssh: connect to host 192.168.0.32 port 22: No route to host'
  unreachable: true
fatal: [192.168.0.31]: UNREACHABLE! => changed=false 
  msg: 'Failed to connect to the host via ssh: ssh: connect to host 192.168.0.31 port 22: No route to host'
  unreachable: true
fatal: [192.168.0.33]: UNREACHABLE! => changed=false 
  msg: 'Failed to connect to the host via ssh: ssh: connect to host 192.168.0.33 port 22: No route to host'
  unreachable: true

PLAY RECAP ***********************************************************************************************************************************************************************************
192.168.0.30               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
192.168.0.31               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
192.168.0.32               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
192.168.0.33               : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0  
```

Also attach the console log output contain more details for your reference.
[succeed.txt](https://github.com/harvester/ipxe-examples/files/8925904/succeed.txt)

2022-06-21 23:53 UTC, irishgordo commented
@TachunLin  ahh!  I see where that's coming from now :smile: :sweat_smile: 
yes that error surrounding the `making adjustments` task I was able to find out - that is due to the need of running of:
```
./setup_harvester.sh -cskh
```
the way that the provisioning script currently connects to each harvester node is is through `sshpass` and when they get re-provisioned cleaning the `~/.ssh/known_hosts` file is something that needs to happen.
Passing in `-cskh` or `--clean-ssh-known-hosts` will clean up the `~/.ssh/known_hosts` file to reset it.
If you had that still up and running you could for Harvester node 0 for instance run:
```
            ssh-keygen -f ~/.ssh/known_hosts -R 192.168.0.30;
 ```
 Then `cd` into the root directory of the project and run:
 ```
 VAGRANT_LOG=info DEFAULT_DEBUG=True ansible-playbook ansible/prepare_harvester_nodes.yml --extra-vars "@settings.yml" -i inventory
 ```
 which will prepare the harvester_nodes and re-run that.
 
 Should we make cleaning of the `~/.ssh/known_hosts` file a default behavior?
 Since if it's being re-run and the known_hosts wasn't cleaned, there will be issues unless that flag is passed in?
 There's also a chance that a user may have the ~/.ssh/known_hosts, file in some other location, so there is a flag in the `setup_harvester.sh` script to set the location of the known_hosts file.
 
 I've also pushed a change that allows for the following:
 - provisioning a 'non-airgapped' single node Rancher instance
 - setting the Harvester WebUI / Harvester Dashboard password via the settings.yml (which I feel is really important for us to control so that integration tests will have the Harvester Dashboard password already defined)
 
 Thank you again so much for helping test this big feature :sweat_smile: !

2022-06-23 16:10 UTC, TachunLin commented
@irishgordo, thanks for such detailed investigation and appreciated for adding the 'non-airgapped' single node Rancher feature.

I Tested the latest commit [d8fd305](https://github.com/harvester/ipxe-examples/commit/d8fd305698515ad09649ea91fcddc402c95da146)

* Starting with the `./setup_harvester.sh -cskh`, the first trial I get `ssh connect error` during the rancher box provisioning
The second trial can complete all provisioning towards the `making adjustment` task

```
TASK [making adjustments] ********************************************************************************************************************************************************************
changed: [192.168.0.30]
fatal: [192.168.0.31]: UNREACHABLE! => changed=false
msg: 'Failed to connect to the host via ssh: ssh: connect to host 192.168.0.31 port 22: No route to host'
unreachable: true
fatal: [192.168.0.33]: UNREACHABLE! => changed=false
msg: 'Failed to connect to the host via ssh: ssh: connect to host 192.168.0.33 port 22: No route to host'
unreachable: true
fatal: [192.168.0.32]: UNREACHABLE! => changed=false
msg: 'Failed to connect to the host via ssh: ssh: connect to host 192.168.0.32 port 22: No route to host'
unreachable: true

TASK [make Harvester nodes adjusted for air-gapped rancher] **********************************************************************************************************************************
included: /home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0623/ipxe-examples/vagrant-pxe-harvester/ansible/adjust_harvester_nodes.yml for 192.168.0.30 => (item=0)

TASK [set Harvester Node IP fact for new host group built] ***********************************************************************************************************************************
ok: [192.168.0.30]

TASK [edit hosts with the docker registry domain on harvester node] **************************************************************************************************************************
changed: [192.168.0.30]

TASK [copy rke2 registries over] *******************************************************************************************************************
```

```
davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0623/ipxe-examples/vagrant-pxe-harvester> ./setup_harvester.sh -cskh
Cleaning up VM IPs from ssh hosts file...
Host 192.168.0.30 not found in /home/davidtclin/.ssh/known_hosts
Host 192.168.0.31 not found in /home/davidtclin/.ssh/known_hosts
Host 192.168.0.32 not found in /home/davidtclin/.ssh/known_hosts
Host 192.168.0.33 not found in /home/davidtclin/.ssh/known_hosts
Host 192.168.0.34 not found in /home/davidtclin/.ssh/known_hosts
Starting Ansible Playbooks, running with the configuration on settings.yml...
~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0623/ipxe-examples/vagrant-pxe-harvester ~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0623/ipxe-examples/vagrant-pxe-harvester
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'
[WARNING]: Collection community.general does not support Ansible version 2.10.17
```

* Then I try to access the air gapped rancher, but it looks like can't reach with page not found error
![image](https://user-images.githubusercontent.com/29251855/175286435-1917f418-a775-45fd-a779-07c338d07249.png)


* Then I try building up the non air gapped environment, can complete the provisioning of rancher_box and harvester node
  But have the `failed to connect to the host via ssh` error (By running ` ./setup_harvester.sh -cskh`)
```
ASK [making adjustments] ********************************************************************************************************************************************************************
fatal: [192.168.0.30]: UNREACHABLE! => changed=false
msg: |-
Failed to connect to the host via ssh: @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@ WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED! @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:eFuEMtos3oqTZWa0ifiPF3/CthQy5tfr0Lko0WIa7ps.
Please contact your system administrator.
Add correct host key in /home/davidtclin/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/davidtclin/.ssh/known_hosts:108
You can use following command to remove the offending key:
ssh-keygen -R 192.168.0.30 -f /home/davidtclin/.ssh/known_hosts
Password authentication is disabled to avoid man-in-the-middle attacks.
Keyboard-interactive authentication is disabled to avoid man-in-the-middle attacks.
rancher@192.168.0.30: Permission denied (publickey,password,keyboard-interactive).
unreachable: true
fatal: [192.168.0.33]: UNREACHABLE! => changed=false
msg: 'Failed to connect to the host via ssh: ssh: connect to host 192.168.0.33 port 22: No route to host'
unreachable: true
fatal: [192.168.0.31]: UNREACHABLE! => changed=false
msg: 'Failed to connect to the host via ssh: ssh: connect to host 192.168.0.31 port 22: No route to host'
unreachable: true
fatal: [192.168.0.32]: UNREACHABLE! => changed=false
msg: 'Failed to connect to the host via ssh: ssh: connect to host 192.168.0.32 port 22: No route to host'
unreachable: true

PLAY RECAP ***********************************************************************************************************************************************************************************
192.168.0.30 : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0
192.168.0.31 : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0
192.168.0.32 : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0
192.168.0.33 : ok=0 changed=0 unreachable=1 failed=0 skipped=0 rescued=0 ignored=0
```
![image](https://user-images.githubusercontent.com/29251855/175306940-18a8b8d6-920a-4558-9bf4-728ffcaf3a9a.png)


* Also I try to access the non air-gapped rancher, it also display the page not found error
![image](https://user-images.githubusercontent.com/29251855/175307266-ec716f78-ce46-427d-b5f7-de05153d9871.png)

2022-06-23 16:16 UTC, irishgordo commented
@TachunLin thanks for attaching those logs and that info!
I'll dig into this, I think perhaps trying to see if we can avoid needing to adjust `~/.ssh/known_hosts` entirely.

2022-06-23 22:52 UTC, irishgordo commented
I'm thinking modifying the inventory to just use an ssh key vs username:password is the better approach.
Making some inventory edits that remove:
```
; 192.168.0.30 ansible_host=192.168.0.30 ansible_user=rancher ansible_connection=smart ansible_password=p@ssword
; 192.168.0.31 ansible_host=192.168.0.31 ansible_user=rancher ansible_connection=smart ansible_password=p@ssword
; 192.168.0.32 ansible_host=192.168.0.32 ansible_user=rancher ansible_connection=smart ansible_password=p@ssword
; 192.168.0.33 ansible_host=192.168.0.33 ansible_user=rancher ansible_connection=smart ansible_password=p@ssword
```
listed, but would require an additional entry under `harvester_config.ssh_aauthorized_keys`
and the removal of a lot of content in the setup_harvester.sh script because then that would be no longer needed.

2022-06-23 23:28 UTC, irishgordo commented
I actually think that may have been due to not retrying the helm install that's targeted for non-airgapped.
I pushed up some additional ansible to retry if needed.
Juggling the private key around might be a tad of a hassle, depending if this was to be implemented in a pipeline.
I haven't found a way to silence:
```
fatal: [192.168.0.32]: UNREACHABLE! => changed=false
msg: 'Failed to connect to the host via ssh: ssh: connect to host 192.168.0.32 port 22: No route to host'
unreachable: true
```
I though `ignore_unreachable` would do that, but it seems to be still surfacing that `fatal` error even though the error is to be expected, since there's no logic to determine what nodes are actively running (single-node or up to 3).

2022-06-24 19:07 UTC, irishgordo commented
Because of:
https://github.com/rancher/rancher/issues/37779
Trying for air-gapped to pivot to using Docker and not Helm:
```
    - name: install Rancher via docker for airgapped
      ansible.builtin.command:
        docker run -d --restart=unless-stopped \
        -p 80:80 -p 443:443 \
        -v /home/vagrant/cacerts.pem:/etc/rancher/ssl/cacerts.pem \
        -v /home/vagrant/tls.crt:/etc/rancher/ssl/cert.pem \
        -v /home/vagrant/tls.key:/etc/rancher/ssk/key.pem \
        -e CATTLE_SYSTEM_DEFAULT_REGISTRY={{ settings.rancher_config.registry_domain }}:5000 \
        -e CATTLE_BOOTSTRAP_PASSWORD={{ settings.rancher_config.bootstrap_password }} \
        -e CATTLE_SYSTEM_CATALOG=bundled \
        --privileged {{ settings.rancher_config.registry_domain }}:5000/rancher/rancher:{{ settings.rancher_config.rancher_version }}
      register: running_rancher_via_docker_for_airgap
      retries: 5
      delay: 10
      until: running_rancher_via_docker_for_airgap is success
      when: settings.rancher_config.run_single_node_air_gapped_rancher | bool
 ```
 Testing with 2.6.5, if this works to an extent we can then safely be able to test more recent versions of Rancher.
 As soon as #37779 gets addressed, we can happily pivot back to using k3s.

2022-06-24 23:17 UTC, irishgordo commented
Because of:
https://github.com/rancher/rancher/issues/37779
Trying for air-gapped to pivot to using Docker and not Helm.

Testing with v2.6.5 Rancher / 2.6.5 Rancher
```
    - name: install Rancher via docker for airgapped
      ansible.builtin.command:
        docker run -d --restart=unless-stopped \
        -p 80:80 -p 443:443 \
        -v /home/vagrant/cacerts.pem:/etc/rancher/ssl/cacerts.pem \
        -v /home/vagrant/tls.crt:/etc/rancher/ssl/cert.pem \
        -v /home/vagrant/tls.key:/etc/rancher/ssk/key.pem \
        -e CATTLE_SYSTEM_DEFAULT_REGISTRY={{ settings.rancher_config.registry_domain }}:5000 \
        -e CATTLE_BOOTSTRAP_PASSWORD={{ settings.rancher_config.bootstrap_password }} \
        -e CATTLE_SYSTEM_CATALOG=bundled \
        --privileged {{ settings.rancher_config.registry_domain }}:5000/rancher/rancher:{{ settings.rancher_config.rancher_version }}
      register: running_rancher_via_docker_for_airgap
      retries: 5
      delay: 10
      until: running_rancher_via_docker_for_airgap is success
      when: settings.rancher_config.run_single_node_air_gapped_rancher | bool
 ```
Was running into issues with that, so removed the`.crt` and `.key` file pems seemingly:
```
2022/06/24 20:43:40 [FATAL] failed to setup TLS listener: invalid SSL configuration found, please set both certificate file and certificate key file (one is missing)
INFO: Running k3s server --cluster-init --cluster-reset
Doing /etc/rancher/ssl
```
Then changed the command to:
```
docker run -p 80:80 -p 443:443 --name=helm-install.test -v /home/vagrant/cacerts.pem:/etc/rancher/ssl/cacerts.pem -e CATTLE_SYSTEM_DEFAULT_REGISTRY=myregistry.local:5000 -e CATTLE_BOOTSTRAP_PASSWORD=rancher -e CATTLE_SYSTEM_CATALOG=bundled --privileged myregistry.local:5000/rancher/rancher:v2.6.5
```
Began encountering issues where currently it seems to be trying to still grab system charts and can't resolve them:
```
2022/06/24 22:11:56 [ERROR] Failed to install system chart fleet: pod cattle-system/helm-operation-mlfvr failed, watch closed
2022/06/24 22:12:56 [ERROR] Failed to install system chart fleet-crd: pod cattle-system/helm-operation-k7lwh failed, watch closed
2022/06/24 22:13:56 [ERROR] Failed to install system chart fleet: pod cattle-system/helm-operation-t6ghk failed, watch closed
2022/06/24 22:14:56 [ERROR] Failed to install system chart fleet-crd: pod cattle-system/helm-operation-9q9tk failed, watch closed
2022/06/24 22:15:56 [ERROR] Failed to install system chart fleet-crd: pod cattle-system/helm-operation-xgqmv failed, watch closed
2022/06/24 22:16:56 [ERROR] Failed to install system chart fleet: pod cattle-system/helm-operation-gnndk failed, watch closed
2022/06/24 22:17:57 [ERROR] Failed to install system chart fleet: pod cattle-system/helm-operation-ws8l5 failed, watch closed
2022/06/24 22:18:57 [ERROR] Failed to install system chart fleet-crd: pod cattle-system/helm-operation-q8c7d failed, watch closed
2022/06/24 22:19:57 [ERROR] Failed to install system chart fleet-crd: pod cattle-system/helm-operation-wl5p7 failed, watch closed
2022/06/24 22:20:57 [ERROR] Failed to install system chart fleet: pod cattle-system/helm-operation-lsl5z failed, watch closed
2022/06/24 22:21:57 [ERROR] Failed to install system chart fleet-crd: pod cattle-system/helm-operation-8fzpw failed, watch closed
2022/06/24 22:22:57 [ERROR] Failed to install system chart fleet: pod cattle-system/helm-operation-d2g9m failed, watch closed
2022/06/24 22:23:57 [ERROR] Failed to install system chart fleet: pod cattle-system/helm-operation-6zpm9 failed, watch closed
2022/06/24 22:24:57 [ERROR] Failed to install system chart fleet-crd: pod cattle-system/helm-operation-m685t failed, watch closed
2022/06/24 22:25:57 [ERROR] Failed to install system chart fleet: pod cattle-system/helm-operation-ltpqw failed, watch closed
2022/06/24 22:26:57 [ERROR] Failed to install system chart fleet-crd: pod cattle-system/helm-operation-glh5d failed, watch closed
2022/06/24 22:27:57 [ERROR] Failed to install system chart fleet-crd: pod cattle-system/helm-operation-b99dk failed, watch closed
2022/06/24 22:28:57 [ERROR] Failed to install system chart fleet: pod cattle-system/helm-operation-9qp6n failed, watch closed
2022/06/24 22:29:57 [ERROR] Failed to install system chart fleet: pod cattle-system/helm-operation-dffhb failed, watch closed
2022/06/24 22:30:57 [ERROR] Failed to install system chart fleet-crd: pod cattle-system/helm-operation-8n86d failed, watch closed
```
From on the Vagrant VM, via the `docker exec -it container_id bash` and then running `kubectl get events --all-namespaces` I noticed:
```
cher/shell/manifests/v0.1.16": dial tcp: lookup myregistry.local on 4.2.2.1:53: no such host
cattle-system   7m17s       Warning   Failed                    pod/helm-operation-fn5cb         Error: ErrImagePull
cattle-system   7m17s       Normal    BackOff                   pod/helm-operation-fn5cb         Back-off pulling image "myregistry.local:5000/rancher/shell:v0.1.16"
cattle-system   7m17s       Warning   Failed                    pod/helm-operation-fn5cb         Error: ImagePullBackOff
cattle-system   2m44s       Normal    BackOff                   pod/helm-operation-fn5cb         Back-off pulling image "myregistry.local:5000/rancher/shell:v0.1.16"
cattle-system   7m2s        Warning   Failed                    pod/helm-operation-fn5cb         Error: ImagePullBackOff
cattle-system   4m57s       Normal    Scheduled                 pod/helm-operation-jqc5g         Successfully assigned cattle-system/helm-operation-jqc5g to local-node
cattle-system   4m15s       Normal    Pulling                   pod/helm-operation-jqc5g         Pulling image "myregistry.local:5000/rancher/shell:v0.1.16"
cattle-system   4m15s       Warning   Failed                    pod/helm-operation-jqc5g         Failed to pull image "myregistry.local:5000/rancher/shell:v0.1.16": rpc error: code = Unknown desc = failed to pull and unpack image "myregistry.local:5000/rancher/shell:v0.1.16": failed to resolve reference "myregistry.local:5000/rancher/shell:v0.1.16": failed to do request: Head "https://myregistry.local:5000/v2/rancher/shell/manifests/v0.1.16": dial tcp: lookup myregistry.local on 4.2.2.1:53: no such host
```
I'm not noticing anything that sticks out with `cat /etc/hosts` but I may be missing something:
```
vagrant@rancher-single-node-airgapped:~$ cat /etc/hosts
127.0.0.1	localhost
127.0.1.1	ubuntu2004.localdomain

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters

127.0.0.1 ubuntu2004.localdomain

127.0.2.1 rancher-single-node-airgapped rancher-single-node-airgapped

192.168.0.34 myregistry.local

192.168.0.34 helm-install.test
```
And from inside the running docker container it can talk to the Docker Registry:
```
62a1c2441024:/var/lib/rancher # curl -k https://192.168.0.34:5000/v2/_catalog -H "Accept: application/json"
{"repositories":["quay.io/jetstack/cert-manager-cainjector","quay.io/jetstack/cert-manager-controller","quay.io/jetstack/cert-manager-ctl","quay.io/jetstack/cert-manager-webhook","rancher/aks-operator","rancher/backup-restore-operator","rancher/busybox","rancher/cis-operator","rancher/coredns-coredns","rancher/coreos-kube-state-metrics","rancher/coreos-prometheus-config-reloader","rancher/coreos-prometheus-operator","rancher/eks-operator","rancher/externalip-webhook","rancher/flannel-cni","rancher/fleet","rancher/fleet-agent","rancher/gitjob","rancher/gke-operator","rancher/grafana-grafana","rancher/hardened-calico","rancher/hardened-cluster-autoscaler","rancher/hardened-cni-plugins","rancher/hardened-coredns","rancher/hardened-dns-node-cache","rancher/hardened-etcd","rancher/hardened-flannel","rancher/hardened-ib-sriov-cni","rancher/hardened-k8s-metrics-server","rancher/hardened-kubernetes","rancher/hardened-multus-cni","rancher/hardened-sriov-cni","rancher/hardened-sriov-network-config-daemon","rancher/hardened-sriov-network- [...]

2022-06-24 23:37 UTC, irishgordo commented
Within that kubectl event from the docker container:
```
cher/shell/manifests/v0.1.16": dial tcp: lookup myregistry.local on 4.2.2.1:53: no such host
cattle-system   7m17s       Warning   Failed                    pod/helm-operation-fn5cb         Error: ErrImagePull
cattle-system   7m17s       Normal    BackOff                   pod/helm-operation-fn5cb         Back-off pulling image "myregistry.local:5000/rancher/shell:v0.1.16"
cattle-system   7m17s       Warning   Failed                    pod/helm-operation-fn5cb         Error: ImagePullBackOff
cattle-system   2m44s       Normal    BackOff                   pod/helm-operation-fn5cb         Back-off pulling image "myregistry.local:5000/rancher/shell:v0.1.16"
cattle-system   7m2s        Warning   Failed                    pod/helm-operation-fn5cb         Error: ImagePullBackOff
cattle-system   4m57s       Normal    Scheduled                 pod/helm-operation-jqc5g         Successfully assigned cattle-system/helm-operation-jqc5g to local-node
cattle-system   4m15s       Normal    Pulling                   pod/helm-operation-jqc5g         Pulling image "myregistry.local:5000/rancher/shell:v0.1.16"
cattle-system   4m15s       Warning   Failed                    pod/helm-operation-jqc5g         Failed to pull image "myregistry.local:5000/rancher/shell:v0.1.16": rpc error: code = Unknown desc = failed to pull and unpack image "myregistry.local:5000/rancher/shell:v0.1.16": failed to resolve reference "myregistry.local:5000/rancher/shell:v0.1.16": failed to do request: Head "https://myregistry.local:5000/v2/rancher/shell/manifests/v0.1.16": dial tcp: lookup myregistry.local on 4.2.2.1:53: no such host
```
I do see earlier in the logs outside the docker container on the Vagrant VM:
This:
```
  - '  - ''Loaded image: rancher/shell:v0.1.14'''
    - '  - ''Loaded image: rancher/shell:v0.1.8'''
  - '  - ''Loaded image: rancher/shell:v0.1.16'''
```

Then:
```
  - '  - ''v0.2.7: digest: sha256:c318644f339b090739a68ac0730adca8e5cdd505d0c299486bee1ac3ae8fc7bb size: 2428'''
  - '  - The push refers to repository [myregistry.local:5000/rancher/shell]'
  - '  - ''d14eab0438c8: Preparing'''
  - '  - ''46846981e4f9: Preparing'''
  - '  - ''6f80cb93a282: Preparing'''
  - '  - ''0fc2947196e8: Preparing'''
  - '  - ''1499594d5e23: Preparing'''
  - '  - ''e9ff27506d37: Preparing'''
  - '  - ''eb4bde6b29a6: Preparing'''
  - '  - ''e9ff27506d37: Waiting'''
  - '  - ''eb4bde6b29a6: Waiting'''
  - '  - ''46846981e4f9: Pushed'''
  - '  - ''1499594d5e23: Pushed'''
  - '  - ''d14eab0438c8: Pushed'''
  - '  - ''eb4bde6b29a6: Mounted from rancher/klipper-lb'''
  - '  - ''e9ff27506d37: Pushed'''
  - '  - ''0fc2947196e8: Pushed'''
  - '  - ''6f80cb93a282: Pushed'''
  - '  - ''v0.1.14: digest: sha256:6d3cd636eddc5342bcf67461df20c3d7251cc589764dfe86af868b20f6967f12 size: 1784'''
  - '  - The push refers to repository [myregistry.local:5000/rancher/shell]'
  - '  - ''1a76ecdf960e: Preparing'''
  - '  - ''f4617faebf46: Preparing'''
  - '  - ''ad10b6dc40d2: Preparing'''
  - '  - ''2e6bef37021b: Preparing'''
  - '  - ''f06b4a8a1b39: Preparing'''
  - '  - ''2a853a75ca56: Preparing'''
  - '  - ''eb4bde6b29a6: Preparing'''
  - '  - ''2a853a75ca56: Waiting'''
  - '  - ''eb4bde6b29a6: Waiting'''
  - '  - ''f4617faebf46: Pushed'''
  - '  - ''1a76ecdf960e: Pushed'''
  - '  - ''f06b4a8a1b39: Pushed'''
  - '  - ''eb4bde6b29a6: Layer already exists'''
  - '  - ''2a853a75ca56: Pushed'''
  - '  - ''2e6bef37021b: Pushed'''
  - '  - ''ad10b6dc40d2: Pushed'''
  - '  - ''v0.1.16: digest: sha256:0d6de68c4291f97c358c46fc511a9a651b3d6f371d8c254edbc443a146344583 size: 1784'''
  - '  - The push refers to repository [myregistry.local:5000/rancher/shell]'
  - '  - ''c9ecbf6f5e91: Preparing'''
  - '  - ''36940abc8ded: Preparing'''
  - '  - ''6ef8b13e331d: Preparing'''
  - '  - ''22623073f855: Preparing'''
  - '  - ''e669fe2d5234: Preparing'''
  - '  - ''32f366d666a5: Preparing'''
  - '  - ''32f366d666a5: Waiting'''
  - '  - ''c9ecbf6f5e91: Pushed'''
  - '  - ''22623073f855: Pushed'''
  - '  - ''32f366d666a5: Mounted from rancher/prometheus-auth'''
  - '  - ''e669fe2d5234: Pushed'''
  - '  - ''6ef8b13e331d: Pushed'''
  - '  - ''36940abc8ded: Pushed'''
  ```
  And from the Vagrant VM, via:
  ```
  vagrant@rancher-single-node-airgapped:~$ docker images | grep -ie "shell"
rancher/shell                                                                           v0.1.16                                    9dab16c68e6b   4 months ago    169MB
myregistry.local:5000/rancher/shell                                                     v0.1.16                                    9dab16c68e6b   4 months ago    169MB
rancher/shell                                                                           v0.1.14                                    2a129a26351d   7 months ago    171MB
myregistry.local:5000/rancher/shell                                                     v0.1.14                                    2a129a26351d   7 months ago    171MB
rancher/shell                                                                           v0.1.8                                     4921f8cf3ec4   12 months ago   150MB
myregistry.local:5000/rancher/shell                                                     v0.1.8                                     4921f8cf3ec4   12 months ago   150MB

  ```
So the images for `shell` are present, I'm just not sure at this stage why the Docker container from Rancher running it isn't able to see them...
It might be DNS related...
I'm going to add a custom entry locally to see if that helps.

2022-07-06 12:29 UTC, TachunLin commented
@irishgordo, thanks for the detailed check and update, 

### Test Result 
I verified the latest commit https://github.com/harvester/ipxe-examples/commit/c1a02ea2281b959aa9678ce1ad83c8d960c019e8 for the `non-air gapped` harvester and rancher. 

* Setup configuration:
  - Set `rancher_config.run_single_node_rancher` to true
  - Execute `./setup_harvester.sh -cskh`

* The single Harvester node installed and work as expected, and also process the bootstrap login 
  ![image](https://user-images.githubusercontent.com/29251855/177548980-eff1642b-3825-428a-818d-d222ad0f1540.png)

* The rancher still **not working** with `404 page not found` error 
  ![image](https://user-images.githubusercontent.com/29251855/177550169-d05bbc6a-6f19-4605-8ffe-a4a8bf13aa3a.png)

### Additional Context 
* vagrant pxe install logs: 
[test_0706.log](https://github.com/harvester/ipxe-examples/files/9054675/test_0706.log)
* Rancher box
```
vagrant@rancher-single-node-airgapped:~$ kubectl get pods -A
NAMESPACE                   NAME                                      READY   STATUS      RESTARTS      AGE
cert-manager                cert-manager-76d44b459c-5gn9j             1/1     Running     0             62m
cert-manager                cert-manager-cainjector-9b679cc6-b79h8    1/1     Running     0             62m
kube-system                 local-path-provisioner-6c79684f77-85r85   1/1     Running     0             62m
kube-system                 coredns-d76bd69b-mlnpc                    1/1     Running     0             62m
cert-manager                cert-manager-webhook-57c994b6b9-6mfhz     1/1     Running     0             62m
cert-manager                cert-manager-startupapicheck-ltsr4        0/1     Completed   0             62m
kube-system                 helm-install-traefik-crd-gq2b5            0/1     Completed   0             62m
kube-system                 helm-install-traefik-97wkk                0/1     Completed   1             62m
kube-system                 metrics-server-7cd5fcb6b7-6zn6x           1/1     Running     0             62m
kube-system                 svclb-traefik-2blg7                       2/2     Running     0             61m
kube-system                 traefik-df4ff85d6-8nnw4                   1/1     Running     0             61m
cattle-system               rancher-5cbfb6d965-hkx7m                  1/1     Running     0             62m
cattle-system               rancher-5cbfb6d965-jf9f9                  1/1     Running     1 (61m ago)   62m
cattle-system               rancher-5cbfb6d965-fkmkh                  1/1     Running     1 (61m ago)   62m
cattle-fleet-system         gitjob-6b977748fc-tbjdv                   1/1     Running     0             60m
cattle-fleet-system         fleet-controller-784d6fbcd8-jp89f         1/1     Running     0             60m
cattle-system               rancher-webhook-5b65595df9-wctgc          1/1     Running     0             59m
cattle-fleet-local-system   fleet-agent-699b5fb945-6lttr              1/1     Running     0             59m
cattle-system               helm-operation-shxxx                      0/2     Completed   0             59m
vagrant@rancher-single-node-airgapped:~$ kubectl get deployments -A
NAMESPACE                   NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
cert-manager                cert-manager              1/1     1            1           62m
cert-manager                cert-manager-cainjector   1/1     1            1           62m
kube-system                 local-path-provisioner    1/1     1            1           63m
kube-system                 coredns                   1/1     1            1           63m
cert-manager                cert-manager-webhook      1/1     1            1           62m
kube-system                 metrics-server            1/1     1            1           63m
kube-system                 traefik                   1/1     1            1           61m
cattle-system               rancher                   3/3     3            3           62m
cattle-fleet-system         gitjob                    1/1     1            1           60m
cattle-fleet-system         fleet-controller          1/1     1            1           60m
cattle-system               rancher-webhook           1/1     1            1           59m
cattle-fleet-local-system   fleet-agent               1/1     1            1           59m
vagrant@rancher-single-node-airgapped:~$ kubectl get deployments -A
NAMESPACE                   NAME                      READY   UP-TO-DATE   AVAILABLE   AGE
cert-manager                cert-manager              1/1     1            1           62m
cert-manager                cert-manager-cainjector   1/1     1            1           62m
kube-system                 local-path-provisioner    1/1     1            1           63m
kube-system                 coredns                   1/1     1            1           63m
cert-manager                cert-manager-webhook      1/1     1            1           62m
kube-system                 metrics-server            1/1     1            1           63m
kube-system                 traefik                   1/1     1            1           61m
cattle-system               rancher                   3/3     3            3           62m
cattle-fleet-system         gitjob                    1/1     1            1           60m
cattle-fleet-system         fleet-controller          1/1     1            1           60m
cattle-system               rancher-webhook           1/1     1            1           59m
cattle-fleet-local-system   fleet-agent               1/1     1            1           59m
```

2022-07-08 20:24 UTC, irishgordo commented
Still working to try to get some possible work around up for running fully air-gapped rancher with v2.6.5 & v2.6.6.

There are some open issues in Rancher that concern this:
- https://github.com/rancher/rancher/issues/37993
- https://github.com/rancher/rancher/pull/37772
- https://github.com/rancher/qa-tasks/issues/392
- https://github.com/rancher/rancher/issues/37779

2022-07-14 22:23 UTC, irishgordo commented
This happens intermittently and currently just having a bit of retry of 10 times for it...it's still creating some problems:
```
TASK [Run the equivalent of \"apt-get update\" as a separate step, first] ********", "    task path: /var/lib/jenkins/workspace/harvester-vagrant-installation-test/ipxe-examples/vagrant-pxe-harvester/ansible/setup_rancher_node.yml:21", "    <192.168.0.34> ESTABLISH SSH CONNECTION FOR USER: vagrant", "    <192.168.0.34> SSH: EXEC ssh -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o IdentityFile=/var/lib/jenkins/workspace/harvester-vagrant-installation-test/ipxe-examples/vagrant-pxe-harvester/.vagrant/machines/rancher_box/libvirt/private_key -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User=\"vagrant\"' -o ConnectTimeout=30 -o 'ControlPath=\"/var/lib/jenkins/.ansible/cp/e43e363605\"' 192.168.0.34 '/bin/sh -c '\"'\"'echo ~vagrant && sleep 0'\"'\"''", "    <192.168.0.34> (0, b'/home/vagrant\\n', b'')", "    <192.168.0.34> ESTABLISH SSH CONNECTION FOR USER: vagrant", "    <192.168.0.34> SSH: EXEC ssh -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o IdentityFile=/var/lib/jenkins/workspace/harvester-vagrant-installation-test/ipxe-examples/vagrant-pxe-harvester/.vagrant/machines/rancher_box/libvirt/private_key -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User=\"vagrant\"' -o ConnectTimeout=30 -o 'ControlPath=\"/var/lib/jenkins/.ansible/cp/e43e363605\"' 192.168.0.34 '/bin/sh -c '\"'\"'( umask 77 && mkdir -p \"` echo /home/vagrant/.ansible/tmp `\"&& mkdir \"` echo /home/vagrant/.ansible/tmp/ansible-tmp-1657836467.825322-32062-166684646884691 `\" && echo ansible-tmp-1657836467.825322-32062-166684646884691=\"` echo /home/vagrant/.ansible/tmp/ansible-tmp-1657836467.825322-32062-166684646884691 `\" ) && sleep 0'\"'\"''", "    <192.168.0.34> (0, b'ansible-tmp-1657836467.825322-32062-166684646884691=/home/vagrant/.ansible/tmp/ansible-tmp-1657836467.825322-32062-166684646884691\\n', b'')", "    Using module file /usr/local/lib/python3.8/dist-packages/ansible/modules/apt.py", "    <192.168.0.34> PUT /var/lib/jenkins/.ansible/tmp/ansible-local-32032loubgf6n/tmpr62ojoux TO /home/vagrant/.ansible/tmp/ansible-tmp-1657836467.825322-32062-166684646884691/AnsiballZ_apt.py", "    <192.168.0.34> SSH: EXEC sftp -b - -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o IdentityFile=/var/lib/jenkins/workspace/harvester-vagrant-installation-test/ipxe-examples/vagrant-pxe-harvester/.vagrant/machines/rancher_box/libvirt/private_key -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User=\"vagrant\"' -o ConnectTimeout=30 -o 'ControlPath=\"/var/lib/jenkins/.ansible/cp/e43e363605\"' '[192.168.0.34]'", "    <192.168.0.34> (0, b'sftp> put /var/lib/jenkins/.ansible/tmp/ansible-local-32032loubgf6n/tmpr62ojoux /home/vagrant/.ansible/tmp/ansible-tmp-1657836467.825322-32062-166684646884691/AnsiballZ_apt.py\\n', b'')", "    <192.168.0.34> ESTABLISH SSH CONNECTION FOR USER: vagrant", "    <192.168.0.34> SSH: EXEC ssh -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o IdentityFile=/var/lib/jenkins/workspace/harvester-vagrant-installation-test/ipxe-examples/vagrant-pxe-harvester/.vagrant/machines/rancher_box/libvirt/private_key -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User=\"vagrant\"' -o ConnectTimeout=30 -o 'ControlPath=\"/var/lib/jenkins/.ansible/cp/e43e363605\"' 192.168.0.34 '/bin/sh -c '\"'\"'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1657836467.825322-32062-166684646884691/ /home/vagrant/.ansible/tmp/ansible-tmp-1657836467.825322-32062-166684646884691/AnsiballZ_apt.py && sleep 0'\"'\"''", "    <192.168.0.34> (0, b'', b'')", "    <192.168.0.34> ESTABLISH SSH CONNECTION FOR USER: vagrant", "    <192.168.0.34> SSH: EXEC ssh -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o IdentityFile=/var/lib/jenkins/workspace/harvester-vagrant-installation-test/ipxe-examples/vagrant-pxe-harvester/.vagrant/machines/rancher_box/libvirt/private_key -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User=\"vagrant\"' -o ConnectTimeout=30 -o 'ControlPath=\"/var/lib/jenkins/.ansible/cp/e43e363605\"' -tt 192.168.0.34 '/bin/sh -c '\"'\"'sudo -H -S -n  -u root /bin/sh -c '\"'\"'\"'\"'\"'\"'\"'\"'echo BECOME-SUCCESS-gfbntrmvlahvweontlkysqqlpqangxpz ; /usr/bin/python3 /home/vagrant/.ansible/tmp/ansible-tmp-1657836467.825322-32062-166684646884691/AnsiballZ_apt.py'\"'\"'\"'\"'\"'\"'\"'\"' && sleep 0'\"'\"''", "    Escalation succeeded", "    <192.168.0.34> (1, b'\\r\\n{\"failed\": true, \"msg\": \"Failed to update apt cache: unknown reason\", \"invocation\": {\"module_args\": {\"update_cache\": true, \"update_cache_retries\": 10, \"state\": \"present\", \"update_cache_retry_max_delay\": 12, \"cache_valid_time\": 0, \"purge\": false, \"force\": false, \"upgrade\": null, \"dpkg_options\": \"force-confdef,force-confold\", \"autoremove\": false, \"autoclean\": false, \"fail_on_autoremove\": false, \"only_upgrade\": false, \"force_apt_get\": false, \"allow_unauthenticated\": false, \"allow_downgrade\": false, \"lock_timeout\": 60, \"package\": null, \"deb\": null, \"default_release\": null, \"install_recommends\": null, \"policy_rc_d\": null}}}\\r\\n', b'Shared connection to 192.168.0.34 closed.\\r\\n')", "    <192.168.0.34> Failed to connect to the host via ssh: Shared connection to 192.168.0.34 closed.", "    <192.168.0.34> ESTABLISH SSH CONNECTION FOR USER: vagrant", "    <192.168.0.34> SSH: EXEC ssh -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o IdentityFile=/var/lib/jenkins/workspace/harvester-vagrant-installation-test/ipxe-examples/vagrant-pxe-harvester/.vagrant/machines/rancher_box/libvirt/private_key -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User=\"vagrant\"' -o ConnectTimeout=30 -o 'ControlPath=\"/var/lib/jenkins/.ansible/cp/e43e363605\"' 192.168.0.34 '/bin/sh -c '\"'\"'rm -f -r /home/vagrant/.ansible/tmp/ansible-tmp-1657836467.825322-32062-166684646884691/ > /dev/null 2>&1 && sleep 0'\"'\"''", "    <192.168.0.34> (0, b'', b'')", "    fatal: [arancherbox]: FAILED! => changed=false", "      invocation:", "        module_args:", "          allow_downgrade: false", "          allow_unauthenticated: false", "          autoclean: false", "          autoremove: false", "          cache_valid_time: 0", "          deb: null", "          default_release: null", "          dpkg_options: force-confdef,force-confold", "          fail_on_autoremove: false", "          force: false", "          force_apt_get: false", "          install_recommends: null", "          lock_timeout: 60", "          only_upgrade: false", "          package: null", "          policy_rc_d: null", "          purge: false", "          state: present", "          update_cache: true", "          update_cache_retries: 10", "          update_cache_retry_max_delay: 12", "          upgrade: null", "      msg: 'Failed to update apt cache: unknown reason'", "  ", "    PLAY RECAP *********************************************************************", "    arancherbox               [...]

2022-07-15 14:39 UTC, TachunLin commented
Updated the test result of previous test. Check the result after 10 hours running. 
The installation process have completed the process. 

![image](https://user-images.githubusercontent.com/29251855/179245534-589529bf-237e-4c86-a070-57f1946a4bac.png)


#### Test Result
* Harvester is working, can login with predefined password

* While still can't access rancher, it display `404 page not found`
![image](https://user-images.githubusercontent.com/29251855/179245865-04848818-da7a-4a8e-ae50-13f67c57a0ac.png)

#### Additional Context
The console output log in
[0714.log](https://github.com/harvester/ipxe-examples/files/9121730/0714.log)

2022-07-15 17:09 UTC, irishgordo commented
Ahh, I see there is a bug from the log with:
```
  - TASK [Output airgap_k3s_image_copy_result Debug Msg] ***************************
  - 'task path: /home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0716/ipxe-examples/vagrant-pxe-harvester/ansible/setup_rancher_node.yml:729'
  - 'fatal: [arancherbox]: FAILED! => '
  - '  msg: |-'
  - '    the field ''ignore_errors'' has an invalid value (yes+), and could not be converted to an bool.The error was: The value ''yes+'' is not a valid boolean.  Valid booleans include: ''true'', 1, ''false'', 0, ''on'', ''t'', ''f'', ''n'', ''off'', ''0'', ''y'', ''1'', ''yes'', ''no'''
  - '  '
  - '    The error appears to be in ''/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0716/ipxe-examples/vagrant-pxe-harvester/ansible/setup_rancher_node.yml'': line 729, column 11, but may'
  - '    be elsewhere in the file depending on the exact syntax problem.'
  - '  '
  - '    The offending line appears to be:'
  - '  '
  - '  '
  - '            - name: Output airgap_k3s_image_copy_result Debug Msg'
  - '              ^ here'
  - '...ignoring'
```
I also see a lot of the debug statements, which are ignored on errors have issues:
```
  - '    The task includes an option with an undefined variable. The error was: ''dict object'' has no attribute ''stdout_lines'''
  ```
  It rolled out 2.6.4 successfully:
  ```
    - '  stdout: |-'
  - '    Waiting for deployment spec update to be observed...'
  - '    Waiting for deployment spec update to be observed...'
  - '    Waiting for deployment "rancher" rollout to finish: 0 out of 3 new replicas have been updated...'
  - '    Waiting for deployment "rancher" rollout to finish: 0 of 3 updated replicas are available...'
  - '    Waiting for deployment spec update to be observed...'
  - '    Waiting for deployment "rancher" rollout to finish: 0 of 3 updated replicas are available...'
  - '    Waiting for deployment "rancher" rollout to finish: 1 of 3 updated replicas are available...'
  - '    Waiting for deployment "rancher" rollout to finish: 2 of 3 updated replicas are available...'
  - '    deployment "rancher" successfully rolled out'
  - '  stdout_lines: <omitted>'
  ```
  It seems that there wasn't an issue with 2.6.6, but I think it might be good to scaled down the replicas to zero, then re-rollout.
  It looks like it got a 200 on the url with `https://helm-install.test/dashboard/auth/login` which would be the Rancher dashboard login.
  ```
    - <192.168.0.34> (0, b'', b'')
  - 'ok: [arancherbox] => changed=false '
  - '  accept_ranges: bytes'
  - '  attempts: 1'
  - '  cache_control: no-cache, no-store, must-revalidate'
  - '  connection: close'
  - '  content_length: ''1742'''
  - '  content_type: text/html; charset=utf-8'
  - '  cookies: {}'
  - '  cookies_string: '''''
  - '  date: Fri, 15 Jul 2022 10:33:13 GMT'
  - '  elapsed: 0'
  - '  invocation:'
  - '    module_args:'
  - '      attributes: null'
  - '      body: null'
  - '      body_format: raw'
  - '      client_cert: null'
  - '      client_key: null'
  - '      creates: null'
  - '      dest: null'
  - '      follow_redirects: safe'
  - '      force: true'
  - '      force_basic_auth: false'
  - '      group: null'
  - '      headers: {}'
  - '      http_agent: ansible-httpget'
  - '      method: GET'
  - '      mode: null'
  - '      owner: null'
  - '      remote_src: false'
  - '      removes: null'
  - '      return_content: false'
  - '      selevel: null'
  - '      serole: null'
  - '      setype: null'
  - '      seuser: null'
  - '      src: null'
  - '      status_code:'
  - '      - ''200'''
  - '      timeout: 120'
  - '      unix_socket: null'
  - '      unsafe_writes: false'
  - '      url: https://helm-install.test/dashboard/auth/login'
  - '      url_password: null'
  - '      url_username: null'
  - '      use_proxy: true'
  - '      validate_certs: false'
  - '  last_modified: Thu, 12 May 2022 13:52:25 GMT'
  - '  msg: OK (1742 bytes)'
  - '  redirected: false'
  - '  status: 200'
  - '  url: https://helm-install.test/dashboard/auth/login'
  - '  x_api_cattle_auth: ''false'''
  - '  x_content_type_options: nosniff'
  - '  x_frame_options: SAMEORIGIN'
  ```
  I believe the way it's setting things up right now navigating to that `https://192.168.0.34` IP address may not be working.
  I've been testing navigating to: `https://helm-install.test` which is the hostname url for Rancher that get's generated when the Rancher Templates get built.
 6+ hrs is a really long time :/
 I think there may be some networking things that are taking place that are making retries need to happen often.
 I'm going to dig in, to instead of relying on the default nic for the VM, trying to build a custom one that can speak with a seperate network defined in the DHCP Server...
 I'll also make the additional edits to fix some of the things I mentioned above.
 
 Thank you again @TachunLin  a ton for helping test this all!

2022-07-18 22:17 UTC, irishgordo commented
![Screenshot from 2022-07-18 15-07-31](https://user-images.githubusercontent.com/5370752/179626208-6c2c6aa6-825c-48a4-9466-ad681258fbed.png)

@TachunLin I made some additional edits.
Now 2.6.4 will roll out with 0 replicas, then the desired version of Rancher either v2.6.5||v2.6.6||or-some-new-release will get applied on top of it faster.
I also commented out all the additional debug tasks and that seems to speed things up a bit as well.

I was able to spin up 2.6.6 air-gapped, then navigated to helm-install.test and input the password that was given in the settings.yaml for it.
I also updated the Vagrant file and the dhcp.conf, to be maybe less confusing, since the instance or Rancher could be air-gapped or may not be air-gapped, but it will still be a single node at this point -> until we make future edits to allow us to spin up a highly-available Rancher cluster and integrate it with a single-or-multi-node Harvester cluster.

2022-07-19 01:39 UTC, irishgordo commented
I was also able to with current master iso Harvester and 2.6.6 import Harvester into Rancher

![Screenshot from 2022-07-18 18-37-55](https://user-images.githubusercontent.com/5370752/179645477-6421d7ff-39b7-4510-be1d-8ac78982a831.png)

2022-08-11 09:52 UTC, TachunLin commented
@irishgordo 
Today I verified with latest commit https://github.com/harvester/ipxe-examples/commit/91bb9d61b300ce750a44aef308ed9a40b4f55977 with the following default config value

1. Set `rancher_config.run_single_node_rancher` to `true`
2. Set `harvester_network_config.offline` to `true`
3. `rancher_config.rancher_version` to `2.6.6`

And execute with `./setup_harvester.sh -cskh` 

After 3 trials run, it all failed at the same task `TASK [check connection to google first...so apt update doesn't fail] ***********`
with message
```
msg: 'Status code was -1 and not [200]: Request failed: <urlopen error [Errno 101] Network is unreachable>'
```
![image](https://user-images.githubusercontent.com/29251855/184107874-6698ba78-39b5-44a5-97f5-066f383bc7f4.png)


#### Additional Context
The console output log in 
[0811.log](https://github.com/harvester/ipxe-examples/files/9307723/0811.log)


#### Next Step
I would try to find another test machine to verify it again.

2022-08-11 23:49 UTC, irishgordo commented
> @TachunLin thank you for taking a look at that blush - I have a feeling the additional qemu channel that was introduced in the Vagrant file definition may be causing an issue. I will work to fix this today.

Still trying some edits out locally to see if the adjustments fix the issue

2022-08-12 00:53 UTC, irishgordo commented
I'm thinking it may have just been this:
```
        # libvirt.channel :type => 'unix', :target_name => 'org.qemu.guest_agent.0', :target_type => 'virtio'
        # libvirt.qemu_use_agent = true
```
I did comment those lines out and re-ran and it seems to have set everything up accordingly with:
- offline: false
- run_single_node_rancher: true
- run_single_node_air_gapped_rancher: true


![Screenshot from 2022-08-11 17-51-36](https://user-images.githubusercontent.com/5370752/184265691-93ca3740-b00d-46a9-b877-f04004694030.png)

2022-08-18 14:19 UTC, TachunLin commented
@irishgordo Thank you for checking the error log and commit to fix it.   
Today I run 3 trials of provisioning air gapped rancher on my desktop and laptop machine for the latest commit [dfcbd2d](https://github.com/harvester/ipxe-examples/commit/dfcbd2d31f16a78384390b5cece98c2e984901c6) 

The first and second trials runs on my laptop with default configuration

- `rancher_config.run_single_node_rancher` : true
- `harvester_network_config.offline`: true
- `rancher_config.rancher_version` : 2.6.6

The first start trial with command  `./setup_harvester.sh`
While the second trial start with command `./setup_harvester.sh -cskh`

These two provisioning both failed at the beginning of rancher_box creation 

Error message: 
```
ERROR! couldn't resolve module/action 'community.general.parted'. This often indicates a misspelling, missing collection, or incorrect module path.
  
    The error appears to be in '/home/davidtclin/Documents/Harvester/workspace/Review_PR/ipxe_pr45_0818/ipxe-examples/vagrant-pxe-harvester/ansible/setup_rancher_node.yml': line 64, column 11, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
            # TODO: Start grouping things with 'blocks'! - that way there can be logical grouping to this massive script, block/rescue/always
            - name: Create a new ext4 primary partition
              ^ here
```

### Additional Context
Attach the console output log for reference 
[laptop_2.log](https://github.com/harvester/ipxe-examples/files/9374626/laptop_2.log)

2022-08-18 14:30 UTC, TachunLin commented
While the third trials on my desktop can complete the provisioning for the for the latest commit [dfcbd2d](https://github.com/harvester/ipxe-examples/commit/dfcbd2d31f16a78384390b5cece98c2e984901c6) with default configurations. (It take about 5-6 hours)

The result is the same as the last best status
1. I can get Harvester vip 192.168.0.131 and access Harvester dashboard without error
2. But I still `can't access Rancher dashboard` on 192.168.0.34, encounter the same error
```
page not found
```
![image](https://user-images.githubusercontent.com/29251855/185419430-a2853f78-ccf3-464f-8829-5e7eebcc2ec5.png)
![image](https://user-images.githubusercontent.com/29251855/185419499-aeb4f348-e8e3-41af-8140-c7f4f5973c2f.png)

I thinks that close to the expected result but still need further investigation (at least on my current environment) 
I plan to keep this environment, would you please help to advice some trouble shooting tips thus I can provide more clear information to you

Also attach the console output log, hope it could provide some useful information
[deskopt_1.log](https://github.com/harvester/ipxe-examples/files/9374714/deskopt_1.log)

2022-08-18 19:25 UTC, noahgildersleeve commented
I also tested this and installed the pre-requisites [here](https://github.com/irishgordo/ipxe-examples/blob/feat/2096-air-gapped-rancher-single-node-proof-of-concept/vagrant-pxe-harvester/README.md#prerequisites) and I still got this error
```
ERROR! couldn't resolve module/action 'community.general.parted'. This often indicates a misspelling, missing collection, or incorrect module path.
```

2022-08-19 00:31 UTC, irishgordo commented
@TachunLin & @noahgildersleeve - I amended a commit recently to incorporate a Makefile that should preform the checks for the necessary versions of binary programs and the binaries themselves.

@TachunLin - run the `make check-prereqs` on your laptop as I feel that may show that there are missing dependencies needed to run the project.
That's great that the desktop managed to make it further - there may be a DNS issue that you see on the Desktop as:
- 192.168.0.34, is the Rancher node's address, but it's also setting the hostname by default to `https://helm-install.test`, however that might need to be changed to `helm-install.local` in the `settings.yml` if there are some DNS issues, or you may be able to in your own `/etc/hosts` file add an entry for it like:
```
192.168.0.34    helm-install.test
```
I also noticed that if I was trying to connect to `helm-install.test` and was connected to the VPN I was seeing issues.

Note, the Makefile and the makefile-helper.sh script, currently doesn't actually install the needed versions of the binaries, I wanted to get something out that would hopefully just check for things to start and report back the findings - yet I think we could improve the script to dynamically figure out the distribution it's running on & the package manager that distribution uses to automate the installations.

2022-08-19 20:24 UTC, noahgildersleeve commented
I checked my pre-reqs with `make check-prereqs` and they passed after I updated ansible to a recent version. I ran the `./setup_harvester.sh -c` and it failed. The error ended up including this when trying to connect to the ssh on the vagrant box
```
      msg: 'Status code was -1 and not [200]: Request failed: <urlopen error [Errno -3] Temporary failure in name resolution>'
```

2022-08-20 05:36 UTC, irishgordo commented
@TachunLin I was able to reproduce your error that you have been seeing with the `404 page not found`.
It has to do with an issue with currently the Vagrant VM not being able to do the 'best' things with DNS.

The workaround:
- whatever your settings.yml `rancher_install_domain:` is like `helm-install.test` or `helm-install.local` etc. in order to navigate to the VM, specifically the Rancher instance running on K3s, is only accessible with the hostname (like `helm-install.local` or '.test' etc.) but your laptop/desktop/host computer that's running qemu/kvm, the automation doesn't currently provide a good way to do that so you'd need to modify your host computer's `/etc/hosts` file adding this to the bottom of it:
```
192.168.0.34       helm-install.test
```
I've not tried exploring the plugin of [vagrant-hosts](https://github.com/oscar-stack/vagrant-hosts)
but I was trying [vagrant-dns](https://github.com/BerlinVagrant/vagrant-dns) but running into issues trying to set that up due to conflicting dependencies.

I don't think having to modify your local `/etc/hosts` file is really a great solution but I know that it would unblock it locally.

However this now presents a bit more of a challenge, integrating this into a pipeline - as a Jenkins pipeline that would be running that would spin up the Vagrant VMs - and depending on what the `rancher_install_domain` was set to, that could change everytime - though the Jenkins pipeline could edit it's 'own' `/etc/hosts` file possibly, I definitely wouldn't want to go that route.

One thing I haven't tried is seeing if installing:
- [libnss-mdns](https://packages.debian.org/sid/libnss-mdns)
in the Vagrant VM would allow the host os to navigate to anything that' `.local` - though I believe we may want to just change whatever the `rancher_install_domain` is to be the `rancher_box.vm.hostname` in the Vagrantfile as well, which then may just make it easier.  I'll be looking into that.

2022-08-20 05:41 UTC, irishgordo commented
@noahgildersleeve I reworked how the inventory for vagrant was working the Rancher instance.  It tends to follow existing patterns better, the change may resolve the issue you were seeing.

2022-08-23 01:51 UTC, TachunLin commented
@irishgordo, yesterday I verified the latest commit [56b45f4](https://github.com/harvester/ipxe-examples/commit/56b45f44e00a561ba5a33ce50d7dc1967f028413)

By using default value in settings.yaml and execute `./setup_harvester.sh -c`
The provisioning still failed with 'community.general.parted' error. 

Further check the `/ansible/roles/rancher/tasks/main.yml` 
By removing the preceding `community.general` on line 57, 75, 85 and 95
![image](https://user-images.githubusercontent.com/29251855/186049833-09fafb0d-ea5b-44d2-bfad-2f9ee63587b1.png)

We could bypass the ansible syntax check 

I updated this line for a trial and rerun again. 
This time it failed at `TASK [rancher : Run the equivalent of "apt-get update" as a separate step, first] ***` with the following error

```
msg: 'Status code was -1 and not [200]: Request failed: <urlopen error [Errno -3] Temporary failure in name resolution>'
```

Attached full console log for reference. 
[0822.log](https://github.com/harvester/ipxe-examples/files/9398689/0822.log)

2022-08-24 01:17 UTC, irishgordo commented
@TachunLin I'm wondering why that might be :/ 

Would you be able to paste in what the command: `make check-prereqs` returns?
You might also try running: `ansible-galaxy collection install community.general --force`- that will force the update of the package to the latest version.

Then try rerunning either via: `./setup_harvester.sh -c`

Note, the most recent commit changes the default Rancher hostname to: **helm-install.local** (from the settings.yml) - so **https://helm-install.local** should be able to resolve now.

I believe hostname resolution should be fixed, with the introducing of avahi-daemon - but there might still be some issues.
From testing it locally, it did work for me.

2022-08-24 08:45 UTC, TachunLin commented
@irishgordo, try to verified the latest commit [b552ac9](https://github.com/harvester/ipxe-examples/commit/b552ac92fb9bb29375728d31a9a43b66c45b2b08) with your suggested environment check steps 

This time still encounter the error message `couldn't resolve module/action 'community.general.parted'` 

### Check environment setup 

* Check `ansible --version`
```
davidtclin@localhost:~/Documents/Harvester/workspace/Review_PR/ipxe_pr45_0824/ipxe-examples> ansible --version
ansible 2.9.21
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/davidtclin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.13 (default, Mar 10 2021, 18:30:35) [GCC]
```

* Check installed Ansible Galaxy's Community General module
```
ansible.cfg  inventory    makefile-helper.sh  reinstall_harvester_node.sh  setup_harvester.sh
davidtclin@localhost:~/Documents/Harvester/workspace/Review_PR/ipxe_pr45_0824/ipxe-examples/vagrant-pxe-harvester> ansible-galaxy collection install community.general
Process install dependency map
Starting collection install process
Skipping 'community.general' as it is already installed
```

* Force update the Ansible Galaxy's Community General module 
```
davidtclin@localhost:~/Documents/Harvester/workspace/Review_PR/ipxe_pr45_0824/ipxe-examples/vagrant-pxe-harvester> ansible-galaxy collection install community.general --force
Process install dependency map
Starting collection install process
Installing 'community.general:5.5.0' to '/home/davidtclin/.ansible/collections/ansible_collections/community/general'
```

*  Check pre-req packages `make check-prereqs` 
```
davidtclin@localhost:~/Documents/Harvester/workspace/Review_PR/ipxe_pr45_0824/ipxe-examples/vagrant-pxe-harvester> make check-prereqs
./makefile-helper.sh;

 ...starting... 


...running checks...

sshpass installed running version check...
Greater than or equal to 1.0.9 - we're going to continue, since this should be fine... for sshpass
ansible-galaxy is isntalled, running version check...
Greater than or equal to 2.13.0 - we're going to continue, since this should be fine... for ansible/ansible-galaxy
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')

we need to install community.general... please install: 
  ansible-galaxy collection install community.general; 
 at a version 5.4.0 or higher 

Less than 0.7.0 for vagrant's vagrant-libvirt plugin

...finished checks...
```

* Since I already force upgrade the `community.general` to `5.5.0` in the previous step, thus proceed to the installation

### Installation Steps
* Edit the libvirt.loader = '/usr/share/qemu/OVMF.fd' in Vagrantfile to  `/usr/share/qemu/ovmf-x86_64.bin` for Opensuse 15.3

* Use the default settings.yml value since it already set default as the air gapped Harvester and Rancher 

* Execute `./setup_harvester.sh -c` 

### Result
The rancher_box provisioning failed at `TASK [spin up single node rancher]`  with the following error message:

```
ERROR! couldn't resolve module/action 'community.general.parted'. This often indicates a misspelling, missing collection, or incorrect module path.
  
    The error appears to be in '/home/davidtclin/Documents/Harvester/workspace/Review_PR/ipxe_pr45_0824/ipxe-examples/vagrant-pxe-harvester/ansible/roles/rancher/tasks/main.yml': line 69, column 9, but may
    be elsewhere in the file depending on the exact syntax problem.
  
    The offending line appears to be:
  
          # TODO: Start grouping things with 'blocks'! - that way there can be logical grouping to this massive script, block/rescue/always
          - name: Create a new ext4 primary partition
            ^ here
    ==> rancher_box: Removing domain...
    ==> rancher_box: Deleting the machine folder
  stdout_lines: <omitted>
```

![image](https://user-images.githubusercontent.com/29251855/186372984-b65fb778-239a-4c21-9f93-b33ed26acc8c.png)


Attached full console log for reference.
[0823_fail.log](https://github.com/harvester/ipxe-examples/files/9414429/0823_fail.log)

2022-08-24 08:58 UTC, TachunLin commented
* Execute the `ansible-galaxy collection install community.general --force`
```
davidtclin@localhost:~/Documents/Harvester/workspace/Review_PR/ipxe_pr45_0824/ipxe-examples/vagrant-pxe-harvester> ansible-galaxy collection install community.general --force
Process install dependency map
Starting collection install process
Installing 'community.general:5.5.0' to '/home/davidtclin/.ansible/collections/ansible_collections/community/general'
```

* Execute the `make check-prereqs` 
```
davidtclin@localhost:~/Documents/Harvester/workspace/Review_PR/ipxe_pr45_0824/ipxe-examples/vagrant-pxe-harvester> make check-prereqs
./makefile-helper.sh;

 ...starting... 


...running checks...

sshpass installed running version check...
Greater than or equal to 1.0.9 - we're going to continue, since this should be fine... for sshpass
ansible-galaxy is isntalled, running version check...
Greater than or equal to 2.13.0 - we're going to continue, since this should be fine... for ansible/ansible-galaxy
usage: ansible-galaxy collection [-h] COLLECTION_ACTION ...
ansible-galaxy collection: error: argument COLLECTION_ACTION: invalid choice: 'list' (choose from 'init', 'build', 'publish', 'install')

we need to install community.general... please install: 
  ansible-galaxy collection install community.general; 
 at a version 5.4.0 or higher 

Less than 0.7.0 for vagrant's vagrant-libvirt plugin

...finished checks...

davidtclin@localhost:~/Documents/Harvester/workspace/Review_PR/ipxe_pr45_0824/ipxe-examples/vagrant-pxe-harvester>
```
* Execute `./setup_harvester.sh -c` to provision the air gapped again

It will also encounter the same error as the previous trial. 

Attached full console log for reference.
[0823_fail2.log](https://github.com/harvester/ipxe-examples/files/9414587/0823_fail2.log)

2022-08-24 14:00 UTC, irishgordo commented
@TachunLin it looks like the Makefile check isn't able to really do the best job currently at letting the user know that there is a version conflict.  I wrote the Makefile with Ansible version 2.13.0 already installed.  My guess is the way that older versions of Ansible like the one you have installed (2.9.21) produce different information when queried - as to that the current shell script can't figure out exactly how to proceed. 

I believe if you updated your version of Ansible to 2.13.0 instead of 2.9.21 - and changed your Python version to 3.8 instead of 3.6 - that should fix things.  

In order to make the Makefile check better, I think there's the possibility of spinning up VMs that have older versions of Python & Ansible installed, and testing edits to the Makefile script.

Note you'll want to first upgrade to Python 3.8 from Python 3.6 - then you should be able to upgrade Ansible as 3.8 is a dependency for Ansible:

https://docs.ansible.com/ansible/latest/installation_guide/intro_installation.html

2022-08-24 14:05 UTC, irishgordo commented
If you needed Python 3.6 for some projects but because of this project need Python 3.8 - I'd look into maybe trying to set up something like pyenv , so that you could switch between versions of Python - however setup for pyenv I've ran into issues in the past if I recall:

https://github.com/pyenv/pyenv

2022-08-24 23:56 UTC, irishgordo commented
@TachunLin I'm trying to also push some changes, there may be the chance that since the "default" network doesn't exist that could be causing hostname resolution issues:
```
<network>
  <name>default</name>
  <uuid>9521fb90-03f5-4ebb-bb62-afb50bc77f2d</uuid>
  <forward mode="nat">
    <nat>
      <port start="1024" end="65535"/>
    </nat>
  </forward>
  <bridge name="virbr0" stp="on" delay="0"/>
  <mac address="52:54:00:d9:58:f0"/>
  <ip address="192.168.122.1" netmask="255.255.255.0">
    <dhcp>
      <range start="192.168.122.2" end="192.168.122.254"/>
    </dhcp>
  </ip>
</network>
```

Currently trying to see if I can add and push a public network to the rancher_box so there wouldn't be the need to have a default network in existence for qemu/kvm

2022-08-25 09:07 UTC, TachunLin commented
@irishgordo,
I have one desktop and one laptop machine ever used for validating this enhacement.
My laptop encountered error `couldn't resolve module/action 'community.general.parted'`
While on my desktop can pass the 'community.general.parted' check and proceed.

To reduce the effort of setup and troubleshooting the test environment of the python, Ansible and community.general.parted version.

I tend to validate this issue on my desktop with the latest commit [b552ac9](https://github.com/harvester/ipxe-examples/commit/b552ac92fb9bb29375728d31a9a43b66c45b2b08)

The result is I could pass the `community.general.parted` check but failed at the task
`TASK [rancher : copy avahi-daemon.conf over]`

Below the detailed validation steps for your reference.

### Check environment setup

* Check `ansible --version`
```
davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester> ansible --version
ansible 2.10.17
config file = /home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester/ansible.cfg
configured module search path = ['/home/davidtclin/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
ansible python module location = /usr/lib/python3.6/site-packages/ansible
executable location = /usr/bin/ansible
python version = 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
```

* Check pre-req packages `make check-prereqs`
```
davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester> make check-prereqs
./makefile-helper.sh;

...starting...


...running checks...

sshpass installed running version check...
Greater than or equal to 1.0.9 - we're going to continue, since this should be fine... for sshpass
ansible-galaxy is isntalled, running version check...
Greater than or equal to 2.13.0 - we're going to continue, since this should be fine... for ansible/ansible-galaxy

community.general is installed, checking version...

Less than 5.4.0 community.general
Less than 0.7.0 for vagrant's vagrant-libvirt plugin

...finished checks...

```

### Installation Steps
* Edit the libvirt.loader = '/usr/share/qemu/OVMF.fd' in Vagrantfile to `/usr/share/qemu/ovmf-x86_64.bin` for Opensuse 15.3

* Use the default settings.yml value since it already set default as the air gapped Harvester and Rancher

* Execute `./setup_harvester.sh -c`

### Result
The process failed at `TASK [rancher : copy avahi-daemon.conf over] ` with the following error

```
Could not find or access 'avahi-daemon.conf.j2'
```

More console output
```
The full traceback is:
Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/ansible/plugins/action/template.py", line 95, in run
source = self._find_needle('templates', source)
File "/usr/lib/python3.6/site-packages/ansible/plugins/action/__init__.py", line 1232, in _find_needle
return self._loader.path_dwim_relative_stack(path_stack, dirname, needle)
File "/usr/lib/python3.6/site-packages/ansible/parsing/dataloader.py", line 327, in path_dwim_relative_stack
raise AnsibleFileNotFound(file_name=source, paths=[to_native(p) for p in search])
ansible.errors.AnsibleFileNotFound: Could not find or access 'avahi-daemon.conf.j2'
Searched in:
/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester/ansible/roles/rancher/templates/avahi-daemon.conf.j2
/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester/ansible/roles/rancher/avahi-daemon.conf.j2
/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester/ansible/roles/rancher/tasks/templates/avahi-daemon.conf.j2
/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester/ansible/roles/rancher/tasks/avahi-daemon.conf.j2
/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester/ansible/templates/avahi-daemon.conf.j2
/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester/ansible/avahi-daemon.conf.j2 on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
fatal: [rancher_box]: FAILED! => changed=false
msg: |-
Could not find or access 'avahi-daemon.conf.j2'
Searched in:
/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester/ansible/roles/rancher/templates/avahi-daemon.conf.j2
/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester/ansible/roles/rancher/avahi-daemon.conf.j2
/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester/ansible/roles/rancher/tasks/templates/avahi-daemon.conf.j2
/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester/ansible/roles/rancher/tasks/avahi-daemon.conf.j2
/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester/ansible/templates/avahi-daemon.conf.j2
/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester/ansible/avahi-daemon.conf.j2 on the Ansible Controller.
If you are using a module and expect the file to exist on the remote, see the remote_src option
```

Attached full console log for reference.
[0852_01.log](https://github.com/harvester/ipxe-examples/files/9422846/0852_01.log)

2022-08-25 09:07 UTC, TachunLin commented
Try to force install the community.general package and provision again and try again. 

* Execute the `ansible-galaxy collection install community.general --force`
```
davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester> ansible-galaxy collection install community.general --force
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'community.general:5.5.0' to '/home/davidtclin/.ansible/collections/ansible_collections/community/general'
Downloading https://galaxy.ansible.com/download/community-general-5.5.0.tar.gz to /home/davidtclin/.ansible/tmp/ansible-local-12336wylxtk5t/tmps5fii_16
community.general (5.5.0) was installed successfully
```

* Execute the `make check-prereqs`
```
davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester> ansible-galaxy collection install community.general --force
Starting galaxy collection install process
Process install dependency map
Starting collection install process
Installing 'community.general:5.5.0' to '/home/davidtclin/.ansible/collections/ansible_collections/community/general'
Downloading https://galaxy.ansible.com/download/community-general-5.5.0.tar.gz to /home/davidtclin/.ansible/tmp/ansible-local-12336wylxtk5t/tmps5fii_16
community.general (5.5.0) was installed successfully
davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0825/ipxe-examples/vagrant-pxe-harvester> make check-prereqs
./makefile-helper.sh;

...starting...


...running checks...

sshpass installed running version check...
Greater than or equal to 1.0.9 - we're going to continue, since this should be fine... for sshpass
ansible-galaxy is isntalled, running version check...
Greater than or equal to 2.13.0 - we're going to continue, since this should be fine... for ansible/ansible-galaxy

community.general is installed, checking version...

Greater than or equal to 5.4.0 - we're going to continue, since this should be fine... for community.general
Less than 0.7.0 for vagrant's vagrant-libvirt plugin

...finished checks...

```
* Execute `./setup_harvester.sh -c` to provision the air gapped again

But still failed at the same task `TASK [rancher : copy avahi-daemon.conf over]` with the following error

```
Could not find or access 'avahi-daemon.conf.j2'
```

Attached full console log for reference.
[0825_02.log](https://github.com/harvester/ipxe-examples/files/9423236/0825_02.log)

2022-08-30 16:14 UTC, irishgordo commented
@TachunLin - thank you for checking this :smile: 

There were some changes I pushed late last week that should of fixed that error.
As well as additional changes recently to the `make check-prereqs` helper function.

2022-08-31 13:47 UTC, TachunLin commented
@irishgordo, thanks for the update. 
Today I tested the enhancement on my desktop with the latest commit [13c0728](https://github.com/harvester/ipxe-examples/commit/13c07284d4667f5656774c01b707f910aed56fbb)

### Result 
* Did not encounter the previous `Could not find or access 'avahi-daemon.conf.j2'` failure

* The first trials failed at provisioning rancher_box in the task of get package 
`failed name resolution for www.google.com`

* The second trial can finish provisioning airgapped Harvester node and access it correctly (After 6.5 hours running)
  ![image](https://user-images.githubusercontent.com/29251855/187691649-b8ed8328-ada9-4b5b-a03f-8746ecaf6435.png)

* The second trial can finish provisioning airgapped Rancher box, but still unable to access via IP or hostname
  with error `page not found`
  - Access via https://192.168.0.34
    ![image](https://user-images.githubusercontent.com/29251855/187692499-41f5b453-1725-45b8-b53f-d32034cd0474.png)
    ![image](https://user-images.githubusercontent.com/29251855/187692563-6936ad46-a0b9-486d-b5d9-a773d982d1d0.png)
    
  - Access via https://helm-install.test/
    ![image](https://user-images.githubusercontent.com/29251855/187692157-7ebbc80f-e051-403c-9a51-8a313d94ac29.png)

Below the detailed validation steps for your reference.

### Check environment setup

* Check pre-req packages `make check-prereqs`
```
davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0829/ipxe-examples/vagrant-pxe-harvester> make check-prereqs
./makefile-helper.sh;

 ...starting... 


...running checks...

we must have a network named 'default' that exists with persistence and autostart
something like: 

                <network>
                <name>default</name>
                <uuid>9521fb90-03f5-4ebb-bb62-afb50bc77f2d</uuid>
                <forward mode="nat">
                    <nat>
                    <port start="1024" end="65535"/>
                    </nat>
                </forward>
                <bridge name="virbr0" stp="on" delay="0"/>
                <mac address="52:54:00:d9:58:f0"/>
                <ip address="192.168.122.1" netmask="255.255.255.0">
                    <dhcp>
                    <range start="192.168.122.2" end="192.168.122.254"/>
                    </dhcp>
                </ip>
                </network>
sshpass installed running version check...
Greater than or equal to 1.0.9 - we're going to continue, since this should be fine... for sshpass
ansible-galaxy is isntalled, running version check...
Greater than or equal to 2.13.0 - we're going to continue, since this should be fine... for ansible/ansible-galaxy

community.general is installed, checking version...

Greater than or equal to 5.4.0 - we're going to continue, since this should be fine... for community.general
==> vagrant: A new version of Vagrant is available: 2.3.0 (installed version: 2.2.18)!
==> vagrant: To upgrade visit: https://www.vagrantup.com/downloads.html

Less than 0.7.0 for vagrant's vagrant-libvirt plugin

...finished checks...

```

### Installation Steps
* Edit the libvirt.loader = '/usr/share/qemu/OVMF.fd' in Vagrantfile to `/usr/share/qemu/ovmf-x86_64.bin` for Opensuse 15.3

* Use the default settings.yml value since it already set default as the air gapped Harvester and Rancher

* Execute `./setup_harvester.sh -c`

### Follow up 
I would prefer keeping the current environment for troubleshooting. 
Please advice any steps I could execute to provide more useful information to you.

2022-08-31 18:10 UTC, irishgordo commented
Thanks for re-running that @TachunLin  - it looks like from the check pre-reqs make hook that it can't find a default network.  With:
```
we must have a network named 'default' that exists with persistence and autostart
something like: 

                <network>
                <name>default</name>
                <uuid>9521fb90-03f5-4ebb-bb62-afb50bc77f2d</uuid>
                <forward mode="nat">
                    <nat>
                    <port start="1024" end="65535"/>
                    </nat>
                </forward>
                <bridge name="virbr0" stp="on" delay="0"/>
                <mac address="52:54:00:d9:58:f0"/>
                <ip address="192.168.122.1" netmask="255.255.255.0">
                    <dhcp>
                    <range start="192.168.122.2" end="192.168.122.254"/>
                    </dhcp>
                </ip>
                </network>
```

I'm not sure if `vibr0` is already in use.
I would suggest maybe trying to build the network manually for now and see if re-running it works.

### First Possible Option
Since it can't find the Libvirt 'default' network - you could just try running:
```
# virsh net-define /usr/share/libvirt/networks/default.xml
Network default defined from /usr/share/libvirt/networks/default.xml
# virsh net-autostart default
Network default marked as autostarted
# virsh net-start default
Network default started
```

### Second Possible Option
Since it can't find the Libvirt default network, and if the first option doesn't offer as much control - you could create a file called `default_network.xml` that contained:
```
<network>
<name>default</name>
<uuid>9521fb90-03f5-4ebb-bb62-afb50bc77f2d</uuid>
<forward mode="nat">
    <nat>
    <port start="1024" end="65535"/>
    </nat>
</forward>
<bridge name="virbr0" stp="on" delay="0"/>
<mac address="52:54:00:d9:58:f0"/>
<ip address="192.168.122.1" netmask="255.255.255.0">
    <dhcp>
    <range start="192.168.122.2" end="192.168.122.254"/>
    </dhcp>
</ip>
</network>
```
Then running:
`virsh net-define --validate --file default_network.xml`
To use `virsh` to create the VM Network.
Though you might get an error like:
```
error: Failed to define network from default_network.xml
error: internal error: bridge name 'virbr0' already in use.
```
If it's dealing with the `virbr0` you could just change that in the `default_network.xml` to something like `virbr9`.
Though, it may fail due to another issue, like the dhcp range, then you could change that in the file from like: 192.168.122.X to 192.168.126.X.
Then you would want to make sure the network is turned on and also starts at boot via something like VirtManager.

You could validate that it was setup appropriately with something like:
```
virsh net-list --persistent --autostart --name | grep -e "default"
```
and if that returns default that's good.
Then also just checking:
```
virsh net-list
```
And seeing if 'default' is of State 'active' 


### Rancher's Need for Default Libvirt Network
The Rancher box relies on their being a 'default' network defined.  Usually with something like:
```
sudo apt install qemu qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils dnsmasq-base
```
That would install Libvirt - 
Libvirt comes with a "default" Network installed:
https://wiki.libvirt.org/page/Networking
> Every standard libvirt installation provides NAT based connectivity to virtual machines out of the box. This is the so called 'default virtual network'. You can verify that it is available with 

So I hadn't :sweat_smile:  thought about the fact that someone could have removed the 'default' network from their LIbvirt setup.
Perhaps we could make some additional changes to try to create a default network if it doesn't exist.
Even just possibly leveraging the first option's steps... 
That might be a better future enhancement, but I think this is a good mention - for when this get's rolled out to the prod CI pipeline, we should investigate if the prod boxes still have the 'default' network installed from when Libvirt was installed... I would hope so - but they may not.

2022-09-01 12:32 UTC, TachunLin commented
@irishgordo,

On my desktop environment verifying the enhancement which already have `default` created as the virtual network. 
This only thing not consistent is it not yet set as `autostart` 

I marked the `default` network as `autostart` with the following command 
```virsh net-autostart default``` to mark the default Network as autostarted

And check it have already setup with `virsh net-list --persistent --autostart --name | grep -e "default"`

```
davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0811> virsh net-autostart default
Network default marked as autostarted

davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0811> virsh net-list --persistent --name | grep -e default
default
davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0811> virsh net-list
 Name              State    Autostart   Persistent
----------------------------------------------------
 default           active   yes         yes
 harvester         active   no          yes
 vagrant-libvirt   active   no          yes

```

And I also checked package on my os environment by using `zypper se <package_name>` ( for OpenSuse leap 15.3)
I check all of them on Opensuse OS with the above package name.
Found the following three package can't be found

- libvirt-daemon-system
- libvirt-clients
- dnsmasq-base

And try using `zypper in <package name>` to install these packages 
```
davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0811> sudo zypper in libvirt-daemon-system
[sudo] password for root: 
Retrieving repository 'Update repository with updates from SUSE Linux Enterprise 15' metadata ..........................................................................................[done]
Building repository 'Update repository with updates from SUSE Linux Enterprise 15' cache ...............................................................................................[done]
Loading repository data...
Reading installed packages...
Package 'libvirt-daemon-system' not found.
Resolving package dependencies...
Nothing to do.

davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0811> sudo zypper in libvirt-clients
Loading repository data...
Reading installed packages...
Package 'libvirt-clients' not found.
Resolving package dependencies...
Nothing to do.

davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0811> sudo zypper in dnsmasq-base
Loading repository data...
Reading installed packages...
Package 'dnsmasq-base' not found.
Resolving package dependencies...
Nothing to do.

```

Not sure whether these three package have different name on OpenSuse leap.

2022-09-05 14:09 UTC, TachunLin commented
@irishgordo , I done the following environment check then provisioning the airgapped Rancher again. 
But still get the same `page not found` error for the airgapped rancher_box. 

### Environment Check 
*According to the first possible option in https://github.com/harvester/ipxe-examples/pull/45#issuecomment-1233258687, I try deleting the `default` network and create the new default network in the following manner 

  ```
  # virsh net-define /usr/share/libvirt/networks/default.xml
  Network default defined from /usr/share/libvirt/networks/default.xml
  # virsh net-autostart default
  Network default marked as autostarted
  # virsh net-start default
  Network default started
  ```

  ```
  davidtclin@localhost:~> virsh net-list --all
   Name      State    Autostart   Persistent
  --------------------------------------------
   default   active   yes         yes
  
  davidtclin@localhost:~> virsh net-destroy default
  Network default destroyed
  
  davidtclin@localhost:~> virsh net-define /usr/share/libvirt/networks/default.xml
  error: Failed to define network from /usr/share/libvirt/networks/default.xml
  error: operation failed: network 'default' already exists with uuid 81f55707-8c1d-4721-8c50-9f12afe985ab
  
  davidtclin@localhost:~> virsh net-list --all
   Name   State   Autostart   Persistent
  ----------------------------------------
  
  davidtclin@localhost:~> virsh net-define /usr/share/libvirt/networks/default.xml
  Network default defined from /usr/share/libvirt/networks/default.xml
  
  davidtclin@localhost:~> virsh net-autostart default
  Network default marked as autostarted
  
  davidtclin@localhost:~> virsh net-start default
  Network default started
  
  davidtclin@localhost:~> virsh net-list --all
   Name      State    Autostart   Persistent
  --------------------------------------------
   default   active   yes         yes
  
  ```

* Then Install `dnsmasq-utils` on Opensuse leap for `dnsmasq-base`
  ```
  davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0829/ipxe-examples/vagrant-pxe-harvester> sudo zypper install dnsmasq-utils
  Loading repository data...
  Warning: Repository 'Main Update Repository' appears to be outdated. Consider using a different mirror or server.
  Reading installed packages...
  Resolving package dependencies...
  
  The following NEW package is going to be installed:
    dnsmasq-utils
  
  1 new package to install.
  Overall download size: 40.2 KiB. Already cached: 0 B. After the operation, additional 36.9 KiB will be used.
  Continue? [y/n/v/...? shows all options] (y): y
  Retrieving package dnsmasq-utils-2.86-150100.7.20.1.x86_64                                                                                               (1/1),  40.2 KiB ( 36.9 KiB unpacked)
  Retrieving: dnsmasq-utils-2.86-150100.7.20.1.x86_64.rpm ................................................................................................................................[done]
  
  Checking for file conflicts: ...........................................................................................................................................................[done]
  (1/1) Installing: dnsmasq-utils-2.86-150100.7.20.1.x86_64 ..............................................................................................................................[done]
  
  ```

* And Install `libvirt` again from zypper install
  ```
  davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0829/ipxe-examples/vagrant-pxe-harvester> sudo zypper install libvirt
  [sudo] password for root: 
  Loading repository data...
  Warning: Repository 'Main Update Repository' appears to be outdated. Consider using a different mirror or server.
  Reading installed packages...
  Resolving package dependencies...
  
  The following NEW package is going to be installed:
    libvirt
  
  1 new package to install.
  Overall download size: 82.2 KiB. Already cached: 0 B. No additional space will be used or freed after the operation.
  Continue? [y/n/v/...? shows all options] (y): y
  Retrieving package libvirt-7.1.0-150300.6.29.1.x86_64                                                                                                    (1/1),  82.2 KiB (    0   B unpacked)
  Retrieving: libvirt-7.1.0-150300.6.29.1.x86_64.rpm .........................................................................................................................[done (1.2 KiB/s)]
  
  Checking for file conflicts: ...........................................................................................................................................................[done]
  (1/1) Installing: libvirt-7.1.0-150300.6.29.1.x86_64 ...................................................................................................................................[done]
  ```

* Start provisioning with command `./setup_harvester.sh -c`

### Test Result

After 6.5 hours running, it can finish provisioning airgapped Rancher box, but still unable to access via IP or hostname
with error `page not found`

* Access via https://192.168.0.34/
  ![image](https://user-images.githubusercontent.com/29251855/188465278-b6e371dd-a774-470c-947f-4a31395a7990.png)
  ![image](https://user-images.githubusercontent.com/29251855/188465636-d645db97-f76c-4928-9414-75ad847f9856.png)

* Access via https://helm-install.test/ 
  ![image](https://user-images.githubusercontent.com/29251855/188465688-d8c54d96-0598-481b-bb30-52b6279291ad.png)


Attach the console log and keep the environment for more investigation. 
[0905_fail.log](https://github.com/harvester/ipxe-examples/files/9490425/0905_fail.log)

2022-09-07 16:15 UTC, irishgordo commented
@TachunLin 
Thanks for checking that again.
Interesting about the packages for SUSE being different than Ubuntu based.
I'm thinking that should be fine with what you have.

Had you updated:
https://github.com/harvester/ipxe-examples/blob/13c07284d4667f5656774c01b707f910aed56fbb/vagrant-pxe-harvester/settings.yml#L159
To be `helm-install.test` ?

I'll review your logs, thanks for attaching those to see if I see anything that stands out

2022-09-07 17:05 UTC, irishgordo commented
@TachunLin 
Reviewing the most recent log, here:
```
  - 'task path: /home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0829/ipxe-examples/vagrant-pxe-harvester/ansible/roles/rancher/tasks/main.yml:639'
  - 'skipping: [rancher_box] => changed=false '
  - '  skip_reason: Conditional result was False'
  - ''
  - 'TASK [rancher : install Rancher v2.6.4 before upgrading to desired version] ****'
  - 'task path: /home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0829/ipxe-examples/vagrant-pxe-harvester/ansible/roles/rancher/tasks/main.yml:654'
  - '<192.168.121.16> ESTABLISH SSH CONNECTION FOR USER: vagrant'
  - '<192.168.121.16> SSH: EXEC ssh -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o ''IdentityFile="/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0829/ipxe-examples/vagrant-pxe-harvester/.vagrant/machines/rancher_box/libvirt/private_key"'' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ''User="vagrant"'' -o ConnectTimeout=30 -o ControlPath=/home/davidtclin/.ansible/cp/a08c460f97 192.168.121.16 ''/bin/sh -c ''"''"''echo ~vagrant && sleep 0''"''"'''''
  - <192.168.121.16> (0, b'/home/vagrant\n', b'')
  - '<192.168.121.16> ESTABLISH SSH CONNECTION FOR USER: vagrant'
  - '<192.168.121.16> SSH: EXEC ssh -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o ''IdentityFile="/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0829/ipxe-examples/vagrant-pxe-harvester/.vagrant/machines/rancher_box/libvirt/private_key"'' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ''User="vagrant"'' -o ConnectTimeout=30 -o ControlPath=/home/davidtclin/.ansible/cp/a08c460f97 192.168.121.16 ''/bin/sh -c ''"''"''( umask 77 && mkdir -p "` echo /home/vagrant/.ansible/tmp `"&& mkdir "` echo /home/vagrant/.ansible/tmp/ansible-tmp-1662381436.7698298-15619-140960143420673 `" && echo ansible-tmp-1662381436.7698298-15619-140960143420673="` echo /home/vagrant/.ansible/tmp/ansible-tmp-1662381436.7698298-15619-140960143420673 `" ) && sleep 0''"''"'''''
  - <192.168.121.16> (0, b'ansible-tmp-1662381436.7698298-15619-140960143420673=/home/vagrant/.ansible/tmp/ansible-tmp-1662381436.7698298-15619-140960143420673\n', b'')
  - Using module file /usr/lib/python3.6/site-packages/ansible/modules/command.py
  - <192.168.121.16> PUT /home/davidtclin/.ansible/tmp/ansible-local-17995dbcahcmv/tmpkwgjuv5y TO /home/vagrant/.ansible/tmp/ansible-tmp-1662381436.7698298-15619-140960143420673/AnsiballZ_command.py
  - '<192.168.121.16> SSH: EXEC sftp -b - -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o ''IdentityFile="/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0829/ipxe-examples/vagrant-pxe-harvester/.vagrant/machines/rancher_box/libvirt/private_key"'' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ''User="vagrant"'' -o ConnectTimeout=30 -o ControlPath=/home/davidtclin/.ansible/cp/a08c460f97 ''[192.168.121.16]'''
  - <192.168.121.16> (0, b'sftp> put /home/davidtclin/.ansible/tmp/ansible-local-17995dbcahcmv/tmpkwgjuv5y /home/vagrant/.ansible/tmp/ansible-tmp-1662381436.7698298-15619-140960143420673/AnsiballZ_command.py\n', b'')
  - '<192.168.121.16> ESTABLISH SSH CONNECTION FOR USER: vagrant'
  - '<192.168.121.16> SSH: EXEC ssh -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o ''IdentityFile="/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0829/ipxe-examples/vagrant-pxe-harvester/.vagrant/machines/rancher_box/libvirt/private_key"'' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ''User="vagrant"'' -o ConnectTimeout=30 -o ControlPath=/home/davidtclin/.ansible/cp/a08c460f97 192.168.121.16 ''/bin/sh -c ''"''"''chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1662381436.7698298-15619-140960143420673/ /home/vagrant/.ansible/tmp/ansible-tmp-1662381436.7698298-15619-140960143420673/AnsiballZ_command.py && sleep 0''"''"'''''
  - <192.168.121.16> (0, b'', b'')
  - '<192.168.121.16> ESTABLISH SSH CONNECTION FOR USER: vagrant'
  - '<192.168.121.16> SSH: EXEC ssh -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o ''IdentityFile="/home/davidtclin/Documents/Harvester/workspace/review_PR/ipxe_pr45_0829/ipxe-examples/vagrant-pxe-harvester/.vagrant/machines/rancher_box/libvirt/private_key"'' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ''User="vagrant"'' -o ConnectTimeout=30 -o ControlPath=/home/davidtclin/.ansible/cp/a08c460f97 -tt 192.168.121.16 ''/bin/sh -c ''"''"''sudo -H -S -n  -u root /bin/sh -c ''"''"''"''"''"''"''"''"''echo BECOME-SUCCESS-wmtdcdnlskefbyhdmdpikaveozhoests ; /usr/bin/python3 /home/vagrant/.ansible/tmp/ansible-tmp-1662381436.7698298-15619-140960143420673/AnsiballZ_command.py''"''"''"''"''"''"''"''"'' && sleep 0''"''"'''''
  - Escalation succeeded
  - '<192.168.121.16> (0, b''\r\n{"changed": true, "stdout": "wrote /home/vagrant/rancher/templates/serviceAccount.yaml\\nwrote /home/vagrant/rancher/templates/secret.yaml\\nwrote /home/vagrant/rancher/templates/clusterRoleBinding.yaml\\nwrote /home/vagrant/rancher/templates/service.yaml\\nwrote /home/vagrant/rancher/templates/deployment.yaml\\nwrote /home/vagrant/rancher/templates/ingress.yaml", "stderr": "WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml\\nWARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /etc/rancher/k3s/k3s.yaml", "rc": 0, "cmd": ["helm", "--kubeconfig", "/etc/rancher/k3s/k3s.yaml", "template", "rancher", "/home/vagrant/rancher-2.6.4.tgz", "--output-dir", "/home/vagrant", "--no-hooks", "--namespace", "cattle-system", "--set", "hostname=helm-install.local", "--set", "rancherImageTag=v2.6.6", "--set", "rancherImage=myregistry.local:5000/rancher/rancher", "--set", "systemDefaultRegistry=myregistry.local:5000",
    "--set", "bootstrapPassword=rancher", "--set", "useBundledSystemChart=true", "--set", "replicas=0", "--set", "ingress.tls.source=secret", "--set", "privateCA=true", "--validate"], "start": "2022-09-05 12:38:25.548124", "end": "2022-09-05 12:38:27.223359", "delta": "0:00:01.675235", "msg": "", "invocation": {"module_args": {"_raw_params": "helm --kubeconfig /etc/rancher/k3s/k3s.yaml template rancher /home/vagrant/rancher-2.6.4.tgz --output-dir /home/vagrant --no-hooks --namespace cattle-system --set hostname=helm-install.local --set rancherImageTag=v2.6.6 --set rancherImage=myregistry.local:5000/rancher/rancher --set systemDefaultRegistry=myregistry.local:5000 --set bootstrapPassword=rancher --set useBundledSystemChart=true --set replicas=0 --set ingress.tls.source=secret --set privateCA=true --validate", "warn": true, "_uses_shell": false, "stdin_add_newline": true, "strip_empty_ends": true, "argv": null, "chdir": null, "executable": null, "creates": null, "removes": null, "stdin": null}}}\r\n'',
    b''Shared connection to 192.168.121.16 closed.\r\n'')'
  - '<192.168.121.16> ESTABLISH SSH CONNECTION FOR USER: vagrant'
  - '<192.168.121.16> SSH: EXEC ssh -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=22 -o ''IdentityFile="/home/ [...]

2022-09-07 22:30 UTC, khushboo-rancher requested changes
@irishgordo Can we separate the airgap example in a different folder, not disturbing the existing [vagrant-pxe-harvester](https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester) folder?

2022-09-08 13:32 UTC, TachunLin commented
@irishgordo, thanks for checking and remind me to change the configuration. 
I tried setting `rancher_install_domain: helm-install.local` and provision again by running `/setup_harvester.sh -c`

Same as before, the provisioning can complete after 6 hours, but sill can't access the airgapped Rancher as the previous trial. 

* Access `https://192.168.0.34` will get `404 page not found` error
![image](https://user-images.githubusercontent.com/29251855/189131988-1d63e22f-176c-4d52-8b92-574246dbd0c3.png)
![image](https://user-images.githubusercontent.com/29251855/189132392-779ce5de-1a1a-41ba-96b2-6880f4df35e4.png)


* Access `https://helm-install.test/` will get `helm-install.test’s DNS address could not be found.`
![image](https://user-images.githubusercontent.com/29251855/189132189-1f31cbc9-dcbb-4f69-86b1-074f93a3e559.png)


Attach the console log for reference.
[0907_fail.log](https://github.com/harvester/ipxe-examples/files/9527140/0907_fail.log)

I am thinking, did you also test connectivity from your host machine running the ipxe-example or somewhere else. 

This enhancement bring out 4 types of scenarios need to check 
1. Airgapped Rancher with airgapped Harvester
2. Airgapped Rancher with Internet Harvester
3. Airgapped Harvester with Internet Rancher 
4. Internet Harvester with Internet Rancher 

I have a suggestion,to prevent too much effort on troubleshooting `scenario 1 (both airgpapped)` on my test environment, 
I can focusing on the remaining three test scenario of the following first.

2022-09-08 17:13 UTC, irishgordo commented
@khushboo-rancher - we could create a whole separate folder called:
`vagrant-pxe-harvester-with-optional-rancher-and-optional-airgap` 
That folder would hold everything that the `vagrant-pxe-harvester` folder has.
But additionally with all the needed edits to settings, Vagrantfiles, Ansible scripts and more.

I'm fine with that approach.
The current CI would then not be affected in the slightest - so when `harvester/harvester-installer/ci/run_vagrant_install_test.yml` goes forth looking for the `harvester/ipxe-examples/vagrant-pxe-harvester` it won't bother doing anything with the other folder entitled `vagrant-pxe-harvester-with-optional-rancher-and-optional-airgap`

What would be the best naming for that folder?
Just `vagrant-pxe-harvester-rancher` (since Rancher is optional & can be optionally air-gapped?)

2022-09-08 17:44 UTC, khushboo-rancher commented
@irishgordo `vagrant-pxe-airgap-harvester` should be good as the goal is to achieve airgap harvester.

2022-09-08 21:52 UTC, irishgordo commented
@TachunLin I was able to replicate your issue - I ended up having some things that were cached prior.
Based around the Avahi implementation that was added.
The `rancher_install_domain` must end in a ".local" so it can be anything as long as it ends in ".local".
I've updated the default setting for it.
I also prior had left a comment above that `settings.yml` line that I forgot to mention earlier this week.
https://github.com/irishgordo/ipxe-examples/blob/feat/2096-air-gapped-rancher-single-node-proof-of-concept/vagrant-pxe-harvester/settings.yml#L159-L160

I had previously created a DNS entry that routed directly `helm-install.test` to the Vagrant VM IP.
So I removed that.
And I also changed it to `helm-installl.test` and I was able to reproduce.
The problem is that Avahi, that runs on the Vagrant VM doesn't work with hostnames that end in ".test" or anything besides ".local".

![Screenshot from 2022-09-08 14-04-44](https://user-images.githubusercontent.com/5370752/189229764-0da67947-7959-429e-aab7-ada6be08d6d1.png)

However, when that gets changed to:
`rancher_install_domain: rancher-vagrant-vm..local` 
Since that ends in ".local" - it should always work:

![Screenshot from 2022-09-08 14-46-30](https://user-images.githubusercontent.com/5370752/189231763-4ec4ec8a-2b58-49c1-ab3b-92525e870376.png)

( navigating to https://rancher-vagrant-vm.local in the browser )

I believe @noahgildersleeve  was able to validate:
> 1. Airgapped Rancher with airgapped Harvester

If you wanted to look at the other 3 scenarios.
But I know it would be great to still see the 1st scenario work for you :smile: .

2022-09-12 17:05 UTC, irishgordo commented
We will need to keep 2.6.4 as the initial Rancher version used and continue to upgrade until this:
https://github.com/rancher/rancher/issues/37993
Can be fixed in 2.7.0
But even then, if we want to test older versions of Rancher, we'll need to keep the logic of first:
- install 2.6.4
- then upgrade 2.6.4 (via helm) to the desired Rancher version
Unless, the desired version is 2.7.0 or greater, then we can just go straight to installing that (pending that some edits get brought in to allow for the bootstrap password to work)

2022-09-14 03:11 UTC, TachunLin commented
@irishgordo, thanks for the checking and the changes. 
I can keep checking the fully airgapped scenario works on my environment and also validate the rest scenarios. 

I first validate the re-structured commit [0708553](https://github.com/harvester/ipxe-examples/pull/45/commits/07085533fb237b2cf8f80cbafbd6e8ca098a14c4) 

Now the Rancher airgapped feature located in the separate folder `vagrant-pxe-airgap-harvester` 
By checking the `settings.yml`, I notice the `rancher_install_domain` changed to `rancher-vagrant-vm.local`

The airgapped environment can successfully provisioning to the end. 
When finished, I checked the connectivity in order:

1. Can access airgapped Harvester via `192.168.0.131` and display dashboard 
2. Can access airgapped Rancher via `192.168.0.34` but display **page not found** error
  ![image](https://user-images.githubusercontent.com/29251855/190049087-738f6c7a-a390-4490-b618-63789de3fe16.png)
3. **Can't** access airgapped Rancher via `https://rancher-vagrant-vm.local`
  ![image](https://user-images.githubusercontent.com/29251855/190049197-0b933833-f647-4d8b-b8d3-bf490a49ee31.png)

4. **Can't** access airgapped Rancher via `https://helm-install.local/` nor the `https://https//helm-install.test` 
  ![image](https://user-images.githubusercontent.com/29251855/190049305-9f14e3f3-7275-4eaa-b1c6-333367e94154.png)
  ![image](https://user-images.githubusercontent.com/29251855/190049332-5c3239c6-3ff0-4124-bb6c-68964427ded5.png)


Attach the console log for reference.
[console_0913.log](https://github.com/harvester/ipxe-examples/files/9562316/console_0913.log)

2022-09-14 03:20 UTC, irishgordo commented
@TachunLin - thank you for checking this again :smile: 

Would you be able to post what `virsh net-dumpxml default` returns?

2022-09-14 03:23 UTC, TachunLin commented
@irishgordo, 

I would like to confirm how to set the configuration in settings.yml to verify the following sceanrios.

1. Airgapped Rancher with Internet Harvester
2. Airgapped Harvester with Internet Rancher
3. Internet Harvester with Internet Rancher

In my understanding, I need to set the following: 
* harvester_network_config.`offline`
* rancher_config.`run_single_node_rancher`
* rancher_config.`run_single_node_air_gapped_rancher`

Should I set the configuration like the following matrix for above scenarios ?
|                                      | offline | run_single_node_rancher | run_single_node_air_gapped_rancher |
|--------------------------------------|---------|-------------------------|------------------------------------|
| Airgapped Rancher Internet Harvester | false   | true                    | true                               |
| Airgapped Harvester Internet Rancher | true    | true                    | false                              |
| Internet Harvester Internet Rancher  | false   | true                    | false                              |

2022-09-14 03:24 UTC, TachunLin commented
The return output of `virsh net-dumpxml default`

```
davidtclin@localhost:~/Documents/Harvester/workspace/review_PR/ipxe_pr45_0908/ipxe-examples/vagrant-pxe-airgap-harvester> virsh net-dumpxml default
<network>
  <name>default</name>
  <uuid>be14010f-983e-492c-8c97-540fa3224ba2</uuid>
  <forward mode='nat'>
    <nat>
      <port start='1024' end='65535'/>
    </nat>
  </forward>
  <bridge name='virbr0' stp='on' delay='0'/>
  <mac address='52:54:00:6a:28:20'/>
  <ip address='192.168.122.1' netmask='255.255.255.0'>
    <dhcp>
      <range start='192.168.122.2' end='192.168.122.254'/>
    </dhcp>
  </ip>
</network>

```

2022-09-14 03:35 UTC, irishgordo commented
@TachunLin  looking over the `virsh net-dumpxml default` it looks as I was expecting it to look so that should be good.
Thanks for sharing that.

As far as the configuration matrix I'd say that all looks pretty spot on :smile: :

|   | harvester_network_config.offline  | rancher_config.run_single_node_rancher  | rancher_config.run_single_node_air_gapped_rancher  |   |
|---|---|---|---|---|
| Air-Gapped Harvester with Air-Gapped Rancher  | true  | true  | true  |   |
|  Air-Gapped Harvester with Internet Rancher  | true  | true  | false  |   |
|  Internet Harvester with Air-Gapped Rancher  |  false  | true  | true  |   |
|  Internet Harvester with Internet Rancher  |  false  | true  | false  |   |

2022-09-14 03:44 UTC, irishgordo commented
@TachunLin  if you also did not want to run Rancher but wanted to have Offline/Air-Gapped Harvester - then it would just be:

|   | harvester_network_config.offline  | rancher_config.run_single_node_rancher  | rancher_config.run_single_node_air_gapped  |   |
|---|---|---|---|---|
| air-gapped / offline Harvester and no Rancher  | true  | false  | false  |   |

2022-09-14 03:49 UTC, irishgordo commented
@TachunLin can you access `https://rancher-vagrant-vm.local` if you edit your computer's `/etc/hosts` file?
Adding a line at the bottom of the file of:
```
192.168.0.34	rancher-vagrant-vm.local
```

There's something really strange happening with the hostname resolving in the VM and I'm not sure what.
But adding that to the bottom of your `/etc/hosts` file on your laptop/computer (not in the VM) I believe could fix the hostname resolution issue.

2022-09-14 03:55 UTC, TachunLin commented
@irishgordo, you are right, by adding hostname mapping in `/etc/hosts` 
I could able to access the airgapped dashboard via https://rancher-vagrant-vm.local 

  ![image](https://user-images.githubusercontent.com/29251855/190055746-092832a1-782c-4991-9801-9b6147194f4d.png)
  ![image](https://user-images.githubusercontent.com/29251855/190055790-c5c1c8a2-080e-49c5-8637-a9c9a7015483.png)

2022-09-14 03:57 UTC, irishgordo commented
@TachunLin  
That's great to hear! :smile: 

Although that would mean that in order to access the air-gapped Rancher, you would need to modify `/etc/hosts` ...I know it's not an ideal situation but it could be a temporary work-around.

I'm also curious if you can navigate to any of the following on the Rancher node:
- https://192.168.0.34:5000/v2/_catalog
- https://myregistry.local:5000/v2/_catalog

^ as we also use a *.local prefix for the Docker registry which I thought would be working

2022-09-14 04:04 UTC, TachunLin commented
I could able to access https://192.168.0.34:5000/v2/_catalog
  ![image](https://user-images.githubusercontent.com/29251855/190056877-8f01e08b-5832-4a7b-aa7f-1fd2d12b994f.png)

But failed to access the https://myregistry.local:5000/v2/_catalog
![image](https://user-images.githubusercontent.com/29251855/190056929-6495f393-33b2-4506-8a68-14f3aebec0ef.png)

2022-09-15 22:56 UTC, irishgordo commented
@TachunLin  - I think through the IP accessing the docker registry works - that's good at least it's accessible through that from outside itself :smile:

2022-09-19 13:42 UTC, TachunLin commented
@irishgordo, I verified the latest commit [829032d](https://github.com/harvester/ipxe-examples/commit/829032dd057923c49d0fcbe18a2f8140d6594e43): 

After 6.5 hours running, it failed at `TASK [get original admin token]` with the following error
```
TASK [get original admin token] **************************************************************************************************************************************************************
FAILED - RETRYING: get original admin token (10 retries left).
FAILED - RETRYING: get original admin token (9 retries left).
FAILED - RETRYING: get original admin token (8 retries left).
FAILED - RETRYING: get original admin token (7 retries left).
FAILED - RETRYING: get original admin token (6 retries left).
FAILED - RETRYING: get original admin token (5 retries left).
FAILED - RETRYING: get original admin token (4 retries left).
FAILED - RETRYING: get original admin token (3 retries left).
FAILED - RETRYING: get original admin token (2 retries left).
FAILED - RETRYING: get original admin token (1 retries left).
fatal: [localhost]: FAILED! => changed=false 
  attempts: 10
  elapsed: 3
  msg: 'Status code was -1 and not [201]: Request failed: <urlopen error [Errno 113] No route to host>'
  redirected: false
  status: -1
  url: https://192.168.0.131/v3-public/localProviders/local?action=login

```

![image](https://user-images.githubusercontent.com/29251855/191030807-86c6f946-5b97-421e-8c7f-2bbfab2ad392.png)


* Can access Rancher via https://rancher-vagrant-vm.local/
![image](https://user-images.githubusercontent.com/29251855/191029935-5891bdc4-505c-4db4-9f9c-1bc4b67a0f94.png)

* Can access the https://192.168.0.34:5000/v2/_catalog but the response looks strange
![image](https://user-images.githubusercontent.com/29251855/191030135-142f2d3b-9d26-43eb-820b-2f0aa73087a3.png)

* And still can't access the  https://myregistry.local:5000/v2/_catalog
![image](https://user-images.githubusercontent.com/29251855/191030493-cfab21c7-30af-4da1-9540-5a80c4b07442.png)

Attach the console log and keep the environment for more investigation.
[0919_fail.log](https://github.com/harvester/ipxe-examples/files/9599376/0919_fail.log)

2022-09-19 18:58 UTC, irishgordo commented
@TachunLin I've increased the amount of retries for Harvester to set the admin password on the dashboard automatically.

And I've updated the README of the folder:
https://github.com/irishgordo/ipxe-examples/tree/feat/2096-air-gapped-rancher-single-node-proof-of-concept/vagrant-pxe-airgap-harvester#troubleshoooting--known-issues

To highlight some of the known issues.
I think additionally adding the `myregistry.local` to your `/etc/hosts` as I mention in the troubleshooting & known issues section may resolve that.
Additionally in the README, I highlighted that there is issues with RKE/RKE2 downstream provisioning - I'm thinking there is something missing or some sort of bug with that.

2022-09-20 16:12 UTC, irishgordo commented
@TachunLin -thanks for the update :smile: 

Since it's still a bit of a mystery with how the hostname resolution is taking place - I believe you could add it to your `/etc/hosts` file as a mapping to fix it.  Combining that with the Rancher instance hostname, something like:
`192.168.0.34 rancher-vagrant-vm.local myregistry.local`
That I think would fix it.
I'm not sure why the catalog is looking the way it looks, if that's incorrect.
I will add that as a callout on the README as a known issue.

2022-09-21 09:53 UTC, TachunLin commented
@irishgordo, by adding the hosts mapping `192.168.0.34 rancher-vagrant-vm.local myregistry.local` in `/etc/hosts`

Now I can access `https://myregistry.local:5000/v2/_catalog` and get response
![image](https://user-images.githubusercontent.com/29251855/191474114-c726696c-5ea6-4d34-b5c6-d0faa2bccf91.png)

2022-09-22 01:23 UTC, irishgordo commented
@TachunLin - I've not had a chance to implement these changes:
https://github.com/harvester/ipxe-examples/pull/52/files#diff-c5b12a4ea9ee410cf51cc1d22256a3bae38cff862f87710690c14c4537647f62

Into the setup.
But once those changes get implemented, then all further testing would need to be done on v1.1head / master.
Actually, if this was trying to run right now off of harvester/master artifacts, I believe it would fail, as those harvester-create, harvester-join and other files haven't been updated.

I'm not 100% but I believe currently the ipxe-examples vagrant:
https://github.com/harvester/ipxe-examples/blob/main/vagrant-pxe-harvester/settings.yml#L15-L18

Will not be backwards compatible with lets say like:

<g-emoji class="g-emoji" alias="file_folder" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4c1.png"><img class="emoji" alt="file_folder" src="https://github.githubassets.com/images/icons/emoji/unicode/1f4c1.png" width="20" height="20"></g-emoji> <a href="https://releases.rancher.com/harvester/v1.0.3/harvester-v1.0.3-initrd-amd64" rel="nofollow">harvester-v1.0.3-initrd-amd64</a><br>
<g-emoji class="g-emoji" alias="file_folder" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4c1.png"><img class="emoji" alt="file_folder" src="https://github.githubassets.com/images/icons/emoji/unicode/1f4c1.png" width="20" height="20"></g-emoji> <a href="https://releases.rancher.com/harvester/v1.0.3/harvester-v1.0.3-vmlinuz-amd64" rel="nofollow">harvester-v1.0.3-vmlinuz-amd64</a><br>
<g-emoji class="g-emoji" alias="file_folder" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4c1.png"><img class="emoji" alt="file_folder" src="https://github.githubassets.com/images/icons/emoji/unicode/1f4c1.png" width="20" height="20"></g-emoji> <a href="https://releases.rancher.com/harvester/v1.0.3/harvester-v1.0.3-rootfs-amd64.squashfs" rel="nofollow">harvester-v1.0.3-rootfs-amd64.squashfs</a><br>
<g-emoji class="g-emoji" alias="white_check_mark" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2705.png"><img class="emoji" alt="white_check_mark" src="https://github.githubassets.com/images/icons/emoji/unicode/2705.png" width="20" height="20"></g-emoji> <a href="https://releases.rancher.com/harvester/v1.0.3/harvester-v1.0.3-amd64.sha512" rel="nofollow">harvester-v1.0.3-amd64.sha512</a><br>
<g-emoji class="g-emoji" alias="memo" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4dd.png"><img class="emoji" alt="memo" src="https://github.githubassets.com/images/icons/emoji/unicode/1f4dd.png" width="20" height="20"></g-emoji><a href="https://releases.rancher.com/harvester/v1.0.3/version.yaml" rel="nofollow">harvester-v1.0.3-version.yaml</a>  

As in, v1.0.3 due to the recent changes, I'm not sure will work with the ipxe provisioning.  
I have not tested the latest `main` changes from:
https://github.com/harvester/ipxe-examples/pull/52/files#diff-c5b12a4ea9ee410cf51cc1d22256a3bae38cff862f87710690c14c4537647f62
with v1.0.3 - yet however

2022-11-04 01:31 UTC, irishgordo commented
@TachunLin  - I pushed some changes recently that should allow for us to use any version of harvester (master, v1.1.0, v1.0.3, v1.0.2, v1.0.1, etc.) with some jinja templating edits.
I was able to use v2.6.9 air-gapped Rancher and import master-head Harvester (1 node), successfully :smile:

2022-11-07 09:15 UTC, TachunLin commented
@irishgordo , I tested the latest commit [09d4112](https://github.com/harvester/ipxe-examples/pull/45/commits/09d411239ea8a5bb14ac4737352d4b680bd1d869) 

Can finish the provisioning job of airpagged Rancher `v2.6.9` with Harvester `v1.1.0` on kvm machines 

Checked the following
1. Can provision airgapped Harvester and access dashboard via `192.168.0.131`
2. Can access Rancher via https://rancher-vagrant-vm.local/
![image](https://user-images.githubusercontent.com/29251855/200271445-5cdf5b13-b5ad-4188-81ee-a0733df40b9c.png)
3. Login with password `rancher`
![image](https://user-images.githubusercontent.com/29251855/200271591-3f319c4e-081a-49b4-bac4-84dd2bd68b51.png)
![image](https://user-images.githubusercontent.com/29251855/200271788-7652a4fc-6a33-4e8e-940d-4679e69476ad.png)

4. Can access the https://192.168.0.34:5000/v2/_catalog but the response return empty
![image](https://user-images.githubusercontent.com/29251855/200271967-62f15529-cf28-492c-9226-1fb8be7563fb.png)

5. Can access https://myregistry.local:5000/v2/_catalog and get response
![image](https://user-images.githubusercontent.com/29251855/200272197-b18d6460-3430-4628-9872-568581357895.png)

Next would be check the provisioning on `v1.0.3` Harvester

2022-11-08 01:44 UTC, TachunLin commented
Also can finish the provisioning job of airpagged Rancher `v2.6.9` with Harvester `v1.0.3` on kvm machines 

1. Can provision airgapped Harvester and access dashboard via `192.168.0.131`
2. Can access Rancher via https://rancher-vagrant-vm.local/

2022-12-02 00:09 UTC, irishgordo commented
Currently working to fix `coredns` issue - to allow for RKE1/RKE2 with:
https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.4/images/openSUSE-Leap-15.4.x86_64-1.0.1-NoCloud-Build2.163.qcow2

2022-12-06 17:17 UTC, irishgordo commented
Yesterday push is breaking ansible flow after cutover.
Currently fixing:
```
    Escalation succeeded
    <192.168.121.74> (255, b'', b'Shared connection to 192.168.121.74 closed.\r\n')
    fatal: [rancher_box]: UNREACHABLE! => changed=false
      msg: 'Failed to connect to the host via ssh: Shared connection to 192.168.121.74 closed.'
      unreachable: true
```

2022-12-07 19:43 UTC, irishgordo commented
This PR is being closed in favor of a much cleaner one.
There were several merge conflicts and additional pivots that took place that have created a bit of pain points for rebasing and squashing everything.
Please see:
https://github.com/harvester/ipxe-examples/pull/59

2022-12-07 19:43 UTC, closed without merging