Add DNS support and update include to include_tasks
harvester/ipxe-examples pull request #70
Opened 2023-12-15 19:27 UTC by noahgildersleeve

This PR creates a new entry for both DNS on the harvester node as well as defining it in the DHCP scope for the virtual cluster. I also updated the `include` to `include_tasks` in ansible since those were deprecated.

2023-12-18 04:14 UTC, albinsun requested changes
1. Please help to fix duplicated `ssh_authorized_keys`
2. Works fine in my env.
   ![image](https://github.com/harvester/ipxe-examples/assets/2773781/aa431852-cdd4-45a8-96e9-62db7e041be7)

2023-12-19 23:45 UTC, noahgildersleeve commented on vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2
> +  ssh_authorized_keys:
Thanks Albin, good catch. It seems that this got duplicated during some of the merge resolution. I fixed the PR.

2023-12-19 23:45 UTC, noahgildersleeve commented on vagrant-pxe-harvester/ansible/roles/harvester/templates/config-join.yaml.j2
> +  ssh_authorized_keys:
Thanks Albin, good catch. It seems that this got duplicated during some of the merge resolution. I fixed the PR.

2023-12-19 23:46 UTC, noahgildersleeve commented
Updated with fixes.

2023-12-20 00:56 UTC, albinsun approved these changes
LGTM, thanks.

2023-12-20 19:47 UTC, merged